### ISSUE TITLE
Set up Rubocop

### ISSUE THREAD

**Issue by hortongn** [uclibs/ucrate#10]
Depends on #1

**Comment by hortongn** [comment]
Sufia's .rubocop.yml can be seen here.  They developed it to match the Hydra community's styles:
https://github.com/projecthydra/sufia/blob/master/.rubocop.yml

See also: https://github.com/projecthydra/sufia/blob/master/.rubocop_todo.yml

Sufia is using the `rubocop` and `rubocop-rspec` gems

**Comment by jamesvanmil** [comment]
Probably a good thing to adopt Hydra community styles. We should chat about this as a larger groups, and talk about including Rubocop in our Scholar 3.0 workflows, too.

**Comment by lawhorkl** [comment]
gonna take this as well just to get these out of the way (waiting on feedback for #12)

**Comment by lawhorkl** [comment]
@jamesvanmil when would you like to have this discussion?

**Comment by jamesvanmil** [comment]
This discussion is part of #14, so once that gets to a draft status

**Comment by lawhorkl** [comment]
Gist of rubocop's review of ucrate pre-hydra configs

https://gist.github.com/lawhorkl/c0d780f3193725f8a4983469905dd84a

**Comment by lawhorkl** [comment]
Gist of rubocop's review of ucrate post-hydra configs with customizations for ucrate:

https://gist.github.com/lawhorkl/1592fbf3fd1872e2994ff7a3e4a70e7f
