### ISSUE TITLE
Support Rails 7.0.3

### ISSUE THREAD

**Issue by scherztc** [uclibs/ucrate#1006]
### Descriptive summary

(https://github.com/samvera/maintenance/issues/77 and https://github.com/samvera/maintenance/issues/107)

### Steps to reproduce the behavior

1. Do this
1. Then do this...

### Related work

Link to related issues or prior related work here.

**Comment by Janell-Huyck** [comment]
As of Nov 3, 2023, Rails 7.0.7.1 will fix all bundler-audit Rails vulnerabilities.

**Comment by Janell-Huyck** [comment]
bundler-audit vulnerabilities this should address:
actionpack
actionview
activerecord
activestorage
activesupport
globalid
rails-html-sanitizer

**Comment by scherztc** [comment]
Closed by JIRA : https://ucdts.atlassian.net/browse/LIBSCHOLAR-22
