### ISSUE TITLE
Set robots.txt on scholar-qa

### ISSUE THREAD

**Issue by crowesn** [uclibs/ucrate#1008]
### Descriptive summary

robots.txt appears to be missing or inactive on scholar-qa

QA should have a robots.txt that disallows indexing.

https://duckduckgo.com/?q=site%3Ascholar-qa.uc.edu&t=hx&va=t&ia=web

```
Looks like the file is missing ...
I suspect something with the capistrano deploy for QA isn't right.  
Scholar.uc.edu has a certain robots.txt that allows indexing while all other deploys should not.
```

**Comment by scherztc** [comment]
Closed by JIRA : https://ucdts.atlassian.net/browse/LIBSCHOLAR-24
