### ISSUE TITLE
Update Scholar OS (DEV/QA/PROD) to new version of Red Hat

### ISSUE THREAD

**Issue by scherztc** [uclibs/ucrate#1015]
## RedHat 8 upgrades
- [x] libschdwl1
- [x] libschdal1
- [x] libschqwl1
- [x] libschqwl2
- [x] libschqsl1
- [x] libschqf1l
- [x] libschpwl1
- [x] libschpwl2
- [x] libschpsl1
- [x] libschpfl1

## Post-upgrade fixes

Revert Apache config files
* mv /etc/httpd/httpd.conf.rpmsave to /etc/httpd/httpd.conf
* mv /etc/httpd/conf.d/autoindex.conf.rpmsave /etc/httpd/conf.d/autoindex.conf
* mv /etc/httpd/conf.d/ssl.conf.rpmsave /etc/httpd/conf.d/ssl.conf
* mv /etc/httpd/cofn.modules.d/00-base.conf.rpmsave /etc/httpd/conf.modules.d/00-base.conf
* mv /etc/httpd/cofn.modules.d/00-lua.conf.rpmsave /etc/httpd/conf.modules.d/00-lua.conf
* mv /etc/httpd/cofn.modules.d/00-mpm.conf.rpmsave /etc/httpd/conf.modules.d/00-mpm.conf

Install missing packages
* sudo dnf install ImageMagick
* sudo dnf install ghostscript
* sudo dnf install clamav
* sudo dnf install libgs

Remove old libgs
* sudo rm /usr/lib/libgs.so*

## Remaining tasks on DEV
- [X] Run through manual test script to identify problems
- [X] Test video player for uploaded videos (ffmpeg)
- [x] Test audio player for uploaded audio
- [x] Test virus scanning
- [x] Send Contact Form Email
- [x] Fix PDF thumbnail generation (ghostscript problem) Minimagick Invalid.  Application built on libpng-1.5.10 but running with running with 1.6.34
- [x] Fix office file thumbnail generation (LibreOffice problem)    
————  These things are broken, but not because of the upgrade
- [ ] Fix Embargo (not an upgrade blocker)
- [ ] Fix Universal Viewer on DEV for all image file types (not an upgrade blocker)

## Remaining tasks on QA
- [ ] QA OS upgrades and testing

## Remaining tasks on PROD
- [ ] Production OS upgrades and testing

**Comment by scherztc** [comment]
March 1 : Upgraded DEV Fedora and SOLR server.

**Comment by schaffzr** [comment]
I don't have edit permissions to the original post, below are additions.

## Post-upgrade fixes
#### Remove old libgs
- sudo rm /usr/lib/libgs.so*

#### Install missing packages
- sudo dnf install libgs

**Comment by hortongn** [comment]
@schaffzr Hopefully you have edit permissions on this issues now.  Let me know if not.
