### ISSUE TITLE
Unused parameters : SelectorQuery

### ISSUE THREAD

**Issue by scherztc** [uclibs/ucrate#1078]
### Descriptive summary

Unused parameters passed to Capybara::Queries::SelectorQuery : ["/users/sign_up"]

### Expected behavior

Clean up Unused parameters

### Actual behavior

Extra parameterss

### Steps to reproduce the behavior

1. bundle exec rake spec

**Comment by Janell-Huyck** [comment]
Should be addressed by PR #1108
