### ISSUE TITLE
Unused Parameters  : SelectorQuery - shibboleth

### ISSUE THREAD

**Issue by scherztc** [uclibs/ucrate#1079]
### Descriptive summary

Unused parameters passed to Capybara::Queries::SelectorQuery : ["/users/auth/shibboleth"]

### Expected behavior

No unused parameters

### Actual behavior

Extra parameters

### Steps to reproduce the behavior

1. bundle exec rake spec

**Comment by Janell-Huyck** [comment]
Should be addressed by PR #1108
