### ISSUE TITLE
Unused Parameters : SelectorQuery - contact

### ISSUE THREAD

**Issue by scherztc** [uclibs/ucrate#1080]
### Descriptive summary

Unused parameters passed to Capybara::Queries::SelectorQuery : ["/contact"]

### Expected behavior

No unused parameters

### Actual behavior

Extra parameters
### Steps to reproduce the behavior

1. bundle exec rake spec

**Comment by Janell-Huyck** [comment]
Should be addressed by PR #1108 

Note 11/13/2023: PR 1108 closed without merging.  This issue fixed by PR 1117.

**Comment by Janell-Huyck** [comment]
Duplication of Issue #1078.  Fixed by PR #1117
