### ISSUE TITLE
HUT : _ga Google Analytics partial missing

### ISSUE THREAD

**Issue by scherztc** [uclibs/ucrate#1134]
### Descriptive summary

Missing partial /_ga with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :coffee, :jbuilder]}

### Expected behavior

When upgrading from hyrax 2.9.6 to 3.6, this test broke.

### Steps to reproduce the behavior

1. Do this
1. Then do this...

### Related work

Link to related issues or prior related work here.

**Comment by crowesn** [comment]
This appears resolved on hyrax_3 branch.
```
  Rendered /Users/crowesn/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/hyrax-3.0.0/app/views/_ga.html.erb (0.1ms)
```

**Comment by scherztc** [comment]
Closed by JIRA : https://ucdts.atlassian.net/browse/LIBSCHOLAR-3?atlOrigin=eyJpIjoiOWQwMzg4ZWI2MjFkNDAxZmJhZjhkODgyZTBhMWQzOTciLCJwIjoiaiJ9
