### ISSUE TITLE
HUT : <%= media_display https://github.com/presenter %>

### ISSUE THREAD

**Issue by scherztc** [uclibs/ucrate#1135]
### Descriptive summary

When upgrading from hyrax 2.9.8 to 3.6

 Failure/Error: <%= media_display https://github.com/presenter %>

### Steps to reproduce the behavior

1. Do this
1. Then do this...

### Related work

Link to related issues or prior related work here.

**Comment by Janell-Huyck** [comment]
Here's the extended error message from a test:

> 
ActionView::Template::Error: Devise could not find the `Warden::Proxy` instance on your request environment.
Make sure that your application is loading Devise and Warden as expected and that the `Warden::Manager` middleware is present in your middleware stack.
If you are seeing this on one of your tests, ensure that your tests are either executing the Rails middleware stack or that your tests are using the `Devise::Test::ControllerHelpers` module to inject the `request.env['warden']` object for you.

  0) hyrax/file_sets/show.html.erb shows acrobat download link
     Failure/Error: <%= media_display @presenter %>

     ActionView::Template::Error:
       Devise could not find the `Warden::Proxy` instance on your request environment.
       Make sure that your application is loading Devise and Warden as expected and that the `Warden::Manager` middleware is present in your middleware stack.
       If you are seeing this on one of your tests, ensure that your tests are either executing the Rails middleware stack or that your tests are using the `Devise::Test::ControllerHelpers` module to inject the `request.env['warden']` object for you.
     # ./app/views/hyrax/file_sets/show.html.erb:5:in `_app_views_hyrax_file_sets_show_html_erb__483690133862941759_410880'
     # ./spec/views/hyrax/file_sets/show.html.erb_spec.rb:39:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # Devise::MissingWarden:
     #   Devise could not find the `Warden::Proxy` instance on your request environment.
     #   Make sure that your application is loading Devise and Warden as expected and that the `Warden::Manager` middleware is present in your middleware stack.
     #   If you are seeing this on one of your tests, ensure that your tests are either executing the Rails middleware stack or that your tests are using the `Devise::Test::ControllerHelpers` module to inject the `request.env['warden']` object for you.
     #   ./app/views/hyrax/file_sets/show.html.erb:5:in `_app_views_hyrax_file_sets_show_html_erb__483690133862941759_410880'

**Comment by Janell-Huyck** [comment]
You can duplicate the error running this specific test:
 `./spec/views/hyrax/file_sets/show.html.erb_spec.rb:39`

**Comment by Janell-Huyck** [comment]
See PR# https://github.com/uclibs/ucrate/pull/1149

**Comment by scherztc** [comment]
Closed by JIRA : https://ucdts.atlassian.net/browse/LIBSCHOLAR-13?atlOrigin=eyJpIjoiNGZjNDkwY2FmZmU0NDE3YTgwMjQyMGVjMzEzMTFkOGUiLCJwIjoiaiJ9
