### ISSUE TITLE
HUT :  Broken Controller Test

### ISSUE THREAD

**Issue by scherztc** [uclibs/ucrate#1138]
### Descriptive summary

  568) Hyrax::GenericWorksController#update when the user has write access to the file changing rights when the work has file sets attached prompts to change the files access
       Failure/Error: expect(response).to redirect_to main_app.confirm_hyrax_permission_path(controller.curation_concern, locale: 'en')
       
         Expected response to be a redirect to <http://test.host/concern/permissions/1072/confirm?locale=en> but was a redirect to <http://test.host/concern/generic_works/1072?locale=en>.
         Expected "http://test.host/concern/permissions/1072/confirm?locale=en" to be === "http://test.host/concern/generic_works/1072?locale=en".
       # ./spec/controllers/concerns/scholar/work_controller_behavior_spec.rb:198:in `block (6 levels) in <top (required)>'

### Steps to reproduce the behavior

1. Do this
1. Then do this...

### Related work

Link to related issues or prior related work here.

**Comment by crowesn** [comment]
https://github.com/samvera/hyrax/commit/33a4ea7b29fc1f1cf3b77226facf59beba395bbf

**Comment by crowesn** [comment]
@scherztc 

Progress on this issue is blocked by https://github.com/uclibs/ucrate/issues/1133

**Comment by scherztc** [comment]
Closed by JIRA : https://ucdts.atlassian.net/browse/LIBSCHOLAR-4?atlOrigin=eyJpIjoiYmQ1ZjZiMmYyOTIwNGY3Yjk2NGM3NThiY2U1MmYzZDUiLCJwIjoiaiJ9
