### ISSUE TITLE
Bundle update all gems (keep this issue open)

### ISSUE THREAD

**Issue by hortongn** [uclibs/ucrate#114]
### Descriptive summary

`bundle update` and verify all tests still pass.  Run through manual test script.

**Comment by scherztc** [comment]
Closed by JIRA : https://ucdts.atlassian.net/browse/LIBSCHOLAR-16?atlOrigin=eyJpIjoiNTRkOTI0ZDE2NjNhNGJjMGJjZGRlYmNmOWEwYWZkYmUiLCJwIjoiaiJ9
