### ISSUE TITLE
HUT : Warden Sidebar

### ISSUE THREAD

**Issue by scherztc** [uclibs/ucrate#1140]
### Descriptive summary

620) hyrax/dashboard/_sidebar.html.erb shows Manage Exports link
       Failure/Error: <%= render 'hyrax/dashboard/sidebar/activity', menu: menu %>
       
       ActionView::Template::Error:
         Devise could not find the `Warden::Proxy` instance on your request environment.
         Make sure that your application is loading Devise and Warden as expected and that the `Warden::Manager` middleware is present in your middleware stack.
         If you are seeing this on one of your tests, ensure that your tests are either executing the Rails middleware stack or that your tests are using the `Devise::Test::ControllerHelpers` module to inject the `request.env['warden']` object for you.
       # ./app/views/hyrax/dashboard/_sidebar.html.erb:16:in `_app_views_hyrax_dashboard__sidebar_html_erb___3439139622463494379_1310320'
       # ./spec/views/hyrax/dashboard/_sidebar.html.erb_spec.rb:42:in `block (2 levels) in <top (required)>'
       # ------------------
       # --- Caused by: ---
       # Devise::MissingWarden:
       #   Devise could not find the `Warden::Proxy` instance on your request environment.
       #   Make sure that your application is loading Devise and Warden as expected and that the `Warden::Manager` middleware is present in your middleware stack.
       #   If you are seeing this on one of your tests, ensure that your tests are either executing the Rails middleware stack or that your tests are using the `Devise::Test::ControllerHelpers` module to inject the `request.env['warden']` object for you.
       #   ./app/views/hyrax/dashboard/_sidebar.html.erb:16:in `_app_views_hyrax_dashboard__sidebar_html_erb___3439139622463494379_1310320'

### Steps to reproduce the behavior

1. Do this
1. Then do this...

### Related work

Link to related issues or prior related work here.

**Comment by Janell-Huyck** [comment]
May be fixed in https://github.com/uclibs/ucrate/pull/1149, or be related.

**Comment by crowesn** [comment]
Confirmed fixed by https://github.com/uclibs/ucrate/pull/1149

**Comment by scherztc** [comment]
Closed by JIRA : https://ucdts.atlassian.net/browse/LIBSCHOLAR-12?atlOrigin=eyJpIjoiZTRiMDUwMzU2NjQ3NDEwZmEyNzBjNTFmMGI0ZWZhYTQiLCJwIjoiaiJ9
