### ISSUE TITLE
IIIF Image Viewer (IV): TIFF, GIF and PNG images are not being rendered

### ISSUE THREAD

**Issue by jayanthdeejay** [uclibs/ucrate#116]
### Descriptive summary

When a TIFF/GIF/PNG is image is attached to a work, they are not being rendered by the IV like JPGs are being rendered. 

### Related work
#60 #115 #117

**Comment by scherztc** [comment]
Tested on Nurax : SUCCESSFULL
GIF Test : https://nurax.curationexperts.com/concern/images/vm40xr673?locale=en#?c=0&m=0&s=0&cv=0&xywh=-746%2C-1%2C2909%2C1001
PNG Test : https://nurax.curationexperts.com/concern/images/pn89d6613?locale=en
TIF Test : https://nurax.curationexperts.com/concern/images/w9505051c?locale=en
JP2 Test : https://nurax.curationexperts.com/concern/images/zw12z540z?locale=en

 I also noticed that Nurax has the turbolinks refresh problem, too

**Comment by scherztc** [comment]
Testing on UCrate locally.

**Comment by scherztc** [comment]
Tested on UCrate locally: 
GIF Test : SUCCESSFULL. Needs sidekiq running.  Files must be characterized to display in UV.
PNG Test : SUCCESSFULL. Needs sidekiq running. Files must be characterized to display in UV.
TIFF Test : SUCCESSFULL. Needs sidekiq running. Files must be characterized to display in UV.
JP2: FAILED on ingest :  MiniMagic error - `identify /var/folders/s3/h0q9pxh16w7gpjmb_zv50ymm0000gn/T/mini_magick20180315-69672-1vjszds.jp2` failed with error: identify: no decode delegate for this image format `JP2' @ error/constitute.c/ReadImage/509.

This also broke ingest.  The next time, I tried to ingest any work, I got the LDP gone error. Ldp::Gone ():

 I am researching how to install imageMagick with JP2 support

**Comment by scherztc** [comment]
ImageMagick installation notes : 

You may need to install other image type delegate libraries. For example if this is a JPG2000 image you will need the jasper library. Seehttp://www.imagemagick.org/download/delegates/

http://omeka.org/forums-legacy/topic/imagemagick-jpeg-support/

https://www.btmash.com/article/2014-05-12/installing-imagemagick-jp2-support-centos

sudo ./configure --prefix=/usr CPPFLAGS='-I/usr/include' LDFLAGS='-L/usr/lib' \
--enable-delegate-build --enable-shared --disable-static --disable-opencl --with-openjp2 \
--with-modules --with-quantum-depth=16 --with-gslib --without-wmf --with-rsvg \
--disable-silent-rules --disable-dependency-tracking --disable-openmp --without-pango \
--with-gs-font-dir=/usr/local/share/ghostscript/fonts/ --with-lqr
