### ISSUE TITLE
Set up Simplecov

### ISSUE THREAD

**Issue by hortongn** [uclibs/ucrate#12]
Compare Coveralls vs. simplecov

**Comment by lawhorkl** [comment]
Coveralls pros:

Coveralls cons:
* Costs money per month

Simplecov pros:
* Apparently free
Simplecov cons:

**Comment by lawhorkl** [comment]
Decided to go with Simplecov instead. It is indeed simpler as well as more streamlined. Also, from what I can tell Coveralls is more or less just a coverage tracker that actually uses Simplecov to do all the analysis anyway. No need to reinvent the wheel in my book, and Simplecov runs every time you run specs with no additional commands.

Should be simple enough to make sure your specs do not drop our score!

**Comment by lawhorkl** [comment]
renamed issue to Simplecov
