### ISSUE TITLE
Try Bixby and research if we should go with it

### ISSUE THREAD

**Issue by jayanthdeejay** [uclibs/ucrate#166]
### Descriptive summary

[Bixby](https://github.com/samvera-labs/bixby) gem has RuboCop Defaults for Samvera Community projects. Try it for UCrate and see if it is worth using the gem.

**Comment by flutterflies** [comment]
When I run rubocop with bixby I get this error
```
Error: Unknown Ruby version 2.5 found in `.ruby-version`.
Supported versions: 2.1, 2.2, 2.3, 2.4
```
