### ISSUE TITLE
Port over the recent changes to Scholar's People page

### ISSUE THREAD

**Issue by hortongn** [uclibs/ucrate#181]
### Descriptive summary

Get the People page in UCrate working and looking like it does in Scholar.

See https://github.com/uclibs/scholar_uc/pull/1888 and https://github.com/uclibs/scholar_uc/pull/1900

**Comment by flutterflies** [comment]
I've moved most of the code from scholar over. There are just a few failing specs that need to be fixed https://github.com/uclibs/ucrate/tree/feature/%23181-port-changes-to-user-page
