### ISSUE TITLE
Epic: Port over Scholar's work types

### ISSUE THREAD

**Issue by hortongn** [uclibs/ucrate#197]
### Descriptive summary

Port over all 8 of Scholar's work types to UCrate.

Note: This may get unwieldy quickly.  Break into smaller PRs or issues if needed.  These chunks can be separate issues: College and Department fields, DOIs, license wizard, etc.

UCrate already has a Generic Work that will need to be replaced by Scholar's.

**Comment by scherztc** [comment]
1.  Run work generators and get test passing.
1.  Compare Scholar metadata and port over customizations.
1.  Port over test.
