### ISSUE TITLE
Configure proxies to behave the same as in Scholar

### ISSUE THREAD

**Issue by hortongn** [uclibs/ucrate#203]
### Descriptive summary

Several customizations were made to proxy functionality in Scholar.  Research the changes made and implement those changes in UCrate so proxies behave the same.

Commits in Scholar dealing with proxies:

https://github.com/uclibs/scholar_uc/commit/4a6761c remove proxy_depositor attribute from catalog index view
https://github.com/uclibs/scholar_uc/commit/501acae Adding wait time to let proxy user creation finish before logging out
https://github.com/uclibs/scholar_uc/commit/2030a89 Resolves performance issues during proxy user lookup
https://github.com/uclibs/scholar_uc/commit/719f0d0 write spec for proxy editing
https://github.com/uclibs/scholar_uc/commit/92b5eb4 fix proxy deposit error bug
https://github.com/uclibs/scholar_uc/commit/92d1b85 Allows proxies to edit files on works they submitted
https://github.com/uclibs/scholar_uc/commit/0519455 Hyrax migration: Fix proxy, users, and search feature specs
https://github.com/uclibs/scholar_uc/commit/ea62db1 working proxy removal
https://github.com/uclibs/scholar_uc/commit/fe6cfa4 Allow owner to edit work created by proxy
https://github.com/uclibs/scholar_uc/commit/f5709f5 tweak proxy help statement
https://github.com/uclibs/scholar_uc/commit/07fa2dd add proxy help statement
https://github.com/uclibs/scholar_uc/commit/b9aff42 Auto-populate creator field and switch names for proxy
https://github.com/uclibs/curate/commit/ca5a6da auto populate college and dept for proxies

**Comment by scherztc** [comment]
- [ ] uclibs/scholar_uc@4a6761c remove proxy_depositor attribute from catalog index view
- [ ] uclibs/scholar_uc@501acae Adding wait time to let proxy user creation finish before logging out
- [ ] uclibs/scholar_uc@2030a89 Resolves performance issues during proxy user lookup
- [ ] uclibs/scholar_uc@719f0d0 write spec for proxy editing
- [ ] uclibs/scholar_uc@92b5eb4 fix proxy deposit error bug
- [ ] uclibs/scholar_uc@92d1b85 Allows proxies to edit files on works they submitted
- [ ] uclibs/scholar_uc@0519455 Hyrax migration: Fix proxy, users, and search feature specs
- [ ] uclibs/scholar_uc@ea62db1 working proxy removal
- [ ] uclibs/scholar_uc@fe6cfa4 Allow owner to edit work created by proxy
- [ ] uclibs/scholar_uc@f5709f5 tweak proxy help statement
- [ ] uclibs/scholar_uc@07fa2dd add proxy help statement
- [ ] uclibs/scholar_uc@b9aff42 Auto-populate creator field and switch names for proxy
- [ ] uclibs/curate@ca5a6da auto populate college and dept for proxies

**Comment by scherztc** [comment]
Dashboard : Works you Own / Works you Manage

**Comment by scherztc** [comment]
Email notifications in Hyrax?
Add Proxy?
Remove Proxy?

**Comment by scherztc** [comment]
Can a proxy create new collections?
