### ISSUE TITLE
Migrate Scholar@UC metadata profile for all work types to UCrate.

### ISSUE THREAD

**Issue by scherztc** [uclibs/ucrate#219]
### Descriptive summary

All of the metadata fields should be ported over from Scholar@UC for each worktype:

Generic Works
Student Works
Etds
Images
Documents
Datasets
Articles
Media

### Expected behavior

That all of the metadata fields are ported over from Scholar@UC.

Careful to account for singular/repeatable fields correctly.

### Actual behavior

UCrate only has a Generic Work. 

### Related work

https://github.com/uclibs/ucrate/issues/197

**Comment by newmanld** [comment]
This may generate other issues to be sure that all descriptive fields are in the keyword index, and to verify that facets behave and search as expected.
