### ISSUE TITLE
Deal with complex meta-data problems with work types

### ISSUE THREAD

**Issue by scherztc** [uclibs/ucrate#226]
### Descriptive summary

The following fields will have to be addressed in UCrate. 

1.  Singular / Repeatable - DONE
     1.  alt_description :  The reason that we had to use alt_description in Hyrax 1 was to work around a bug in the keyword search. (https://github.com/uclibs/scholar_uc/issues/155)  I tested it on curly and I believe that is solved in hyrax 2.  See new implementation of keyword search here : https://github.com/uclibs/ucrate/blob/02438b0ade3292427280491a346383345b5570b3/app/controllers/catalog_controller.rb#L184 . Recommendation:  Do NOT implement alt_description.  DONE  
     1.  alt_date_created :  See above. See new implementation of keyword search here: https://github.com/uclibs/ucrate/blob/02438b0ade3292427280491a346383345b5570b3/app/controllers/catalog_controller.rb#L201 Recommendation : Do NOT implement alt_date_created. DONE
     1.  alternate_title - Recommendation :  Add alternate_title to keyword search.  See issue below.DONE
1.  Used differently in Hyrax 2
     1.  resource_type - Is NOT being used in UCrate.  This field is inherited and available from Hyrax but we do not use it in our forms / presenters.  We have created our own genre field to serve this need.  This could be a refactor later.  Recommendation : Create issue to refactor to use provided resource_type instead of genre. DONE.
     1.  rights_statement - We have implemented both rights_statement and license.  Rights_statement needs some contextual help from the locale file.  Recommendation : Create issue for contextual help.  DONE.
     1.  Bibliographic_Citation - Bibliographic_Citation is available through Hyrax but we do not use it in our Scholar application.  We should remove it from app/views/hyrax/base/_attribute_rows.html.erb and app/controllers/catalog_controller.rb.  Recommendation : Create issue for removing bibliographic_citation from our code base. DONE.
1.  No longer using
     1.  keyword - This field is inherited and available from Hyrax but we do not use it in our forms / presenters.  This could be a refactor later.  Recommendation : Create issue to refactor to remove keyword from our application level code base.  DONE

**Comment by scherztc** [comment]
alt_date_created should also be faceted.

**Comment by newmanld** [comment]
In regard to the new Rights statements - I believe it is modeled after the statements found at http://rightsstatements.org/en/

More information also here: https://docs.google.com/document/d/1aInokOIIsgf-B4iMTXU33qYN5B2jA3s91KgWoh7DZ7Q/edit

A value will need to be determined to share metadata with DPLA.  

I propose that we retain this field in all work types but change to optional so that a value won't be required for all prior works.

**Comment by scherztc** [comment]
I am going to make a seperate issue to compare the app/controllers/catalog_controller.rb from scholar 3 to scholar 4.  Examing keyword search fields (alt_title), facets, display fields, show fields, ...

**Comment by scherztc** [comment]
https://github.com/uclibs/ucrate/issues/317
