### ISSUE TITLE
Remove TODO in multiple work type (proxies, trophies, featured) test.

### ISSUE THREAD

**Issue by scherztc** [uclibs/ucrate#232]
Remove the TODO (proxies, trophies, featured) in work type specs.

Proxies
Trophies
Featured Work

spec/models/document_spec.rb
spec/models/dataset_spec.rb
spec/models/etd_spec.rb
spec/models/generic_work_spec.rb
spec/models/image_spec.rb
spec/models/medium_spec.rb
spec/models/student_work_spec.rb

**Comment by scherztc** [comment]
spec/models/document_spec.rb
spec/models/dataset_spec.rb
spec/models/etd_spec.rb
spec/models/generic_work_spec.rb
spec/models/image_spec.rb
spec/models/medium_spec.rb
spec/models/student_work_spec.rb

**Comment by crowesn** [comment]
@scherztc 

Wondering about where you see these TOO DO messages coming from - 
We have model specs for our work types that created by the hyrax generator:
```
# Generated via
#  `rails generate hyrax:work Dataset`
require 'rails_helper'

RSpec.describe Dataset do
  it "has tests" do
    skip "Add your tests here"
  end
end
```

Are these what you're talking about?

**Comment by scherztc** [comment]
Proxies - Callbacks are pulled out of the model and added to a transfer request actor.  Removing test from model.

**Comment by scherztc** [comment]
Featured Work -  The test of featured works is done in the hyrax controller. https://github.com/samvera/hyrax/blob/5a9d1be16ee1a9150646384471992b03aab527a5/spec/controllers/hyrax/featured_works_controller_spec.rb.  Removing test from model.
