### ISSUE TITLE
Port over Scholar's help message for Dataset work types

### ISSUE THREAD

**Issue by hortongn** [uclibs/ucrate#259]
### Descriptive summary

Scholar's dataset works display a flash message at the top the new work page:
`If you would like guidance on submitting a dataset, please read the #{view_context.link_to 'Documenting Data', '/documenting_data', target: '_blank'} help page.`

(see https://scholar.uc.edu/concern/datasets/new for a working example)

Implement this same message for UCrate's dataset work types.

Commit from Scholar:
https://github.com/uclibs/scholar_uc/commit/ba9b15b27bdcb1e98eac5215dbfb6168a2633163

**Comment by chuckgreenman** [comment]
Pushed up branch, one test failed on Travis, couldn't get it to fail locally though.  Restarted testing.
