### ISSUE TITLE
Featured researcher setting doesn't allow image uploads

### ISSUE THREAD

**Issue by hortongn** [uclibs/ucrate#293]
### Descriptive summary

In production Scholar, the featured researcher settings allow you to upload an image from your computer.  In UCrate, however, it only allows you to link to an existing image on the web.

![edit content block scholar uc 1](https://user-images.githubusercontent.com/5639859/42844577-634146a6-89e1-11e8-83f9-4ed7682c8426.png)

We need to tweak the Tinymce editor to allow image uploads.  Like this...

![scholar uc](https://user-images.githubusercontent.com/5639859/42844684-c543db48-89e1-11e8-8a32-922bcca60e59.png)

**Comment by crowesn** [comment]
Drag and drop image only works in Firefox.

**Comment by hortongn** [comment]
@crowesn If you feel that an admin can accomplish what they need to do in Firefox, go ahead and close this issue.  Thanks
