### ISSUE TITLE
Modify batch edit to behave the same as in Scholar

### ISSUE THREAD

**Issue by hortongn** [uclibs/ucrate#305]
### Descriptive summary

Make the needed changes to have the batch edit experience in UCrate be the same as in Scholar.

Compare the steps and screens with Scholar. We should be able to edit the exact same metadata fields in UCrate as we do in Scholar.  Also make sure that the works changed by the batch edit are consistent with Scholar.

https://scholar-dev.uc.edu is a good place to test batch edit for Scholar.

**Comment by scherztc** [comment]
Scholar 3 :

![screen shot 2018-08-22 at 3 04 17 pm](https://user-images.githubusercontent.com/5084562/44485052-6dba7a00-a61d-11e8-9941-a8d7143338ed.png)

**Comment by scherztc** [comment]
UCrate : 

![screen shot 2018-08-22 at 3 10 34 pm](https://user-images.githubusercontent.com/5084562/44485093-95a9dd80-a61d-11e8-81a5-86fe530a5857.png)

**Comment by scherztc** [comment]
- [ ] Remove Contributor
- [ ] Add College
- [ ] Add Program / Department
- [ ] Remove Keyword
- [ ] Remove Resource Type
- [ ] Add Alternate Title
- [ ] Remove Publisher
- [ ] Add Geo Subject
- [ ] Add Note
- [ ] Remove Location
