### ISSUE TITLE
Port over the batch uploader task from Scholar

### ISSUE THREAD

**Issue by hortongn** [uclibs/ucrate#306]
### Descriptive summary

Scholar has a task that imports metadata and files from the command line.  We want to bring this functionality to UCrate.

Example:
```
rake batch:load:works CSV_LOCATION="/Users/vanmiljf/Downloads/sample_batch_metadata.txt" PATH_TO_WORKS="/home/james/batch"
```

The commit that implements this in Scholar is https://github.com/uclibs/scholar_uc/commit/5373feab5405067cfe14646c826465e9fa347f65, but make sure you are using the most recent version of each of the files in that commit.

@jamesvanmil is a good resource for this issue if you have questions.

**Comment by crowesn** [comment]
Investigate these fields (taken from recipes we had to run at migration, maybe they're okay now?).

* time_period
* required_software
* related_url
* geo_subjects
* genre
* degree
* committee_member
* advisor
