### ISSUE TITLE
Port Scholar DOI feature...

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/ucrate#330]
...adding Datacite compatibility, using https://github.com/ndlib/curate_nd/pull/711 as a reference

**Comment by hortongn** [comment]
@bsp3ars https://github.com/uclibs/scholar_uc/pull/993/commits/fc9a593c050a699e86eab026cc275cddeb0681f2

**Comment by bsp3ars** [comment]
Commits that involve DOI's in scholar_uc

- [ ] DOI Minting https://github.com/uclibs/scholar_uc/commit/fc9a593c050a699e86eab026cc275cddeb0681f2 (11/18/2016)

- [ ] Add DOI Minting Actor https://github.com/uclibs/scholar_uc/commit/8e500ebed7dfd8993ad2003a8c6ff164f310598c (11/21/2017)

- [ ] Allow user to edit manually entered DOIs https://github.com/uclibs/scholar_uc/commit/8145c9c09caad8bb089e2eab1335a73c2fee5a27 (1/25/2018)

- [ ] Changes to allow works with a reserved DOI to be updated https://github.com/uclibs/scholar_uc/commit/ced1f465fdcc21bd5f4e2a78dc5b77d5c416622c (2/7/2018)

- [ ] Set DOI status after work deletion https://github.com/uclibs/scholar_uc/commit/9e8f4c01787df35d94a4b2203c72f421caa97dfc (5/22/2018)
