### ISSUE TITLE
Add ability to delete workgroups

### ISSUE THREAD

**Issue by hortongn** [uclibs/ucrate#35]
We need to decide what happens to workgroup memberships after the workgroup is archived.

**Comment by jamesvanmil** [comment]
I recall that we had talked about not deleting workgroups in the traditional sense, but rather archiving them.

**Comment by hortongn** [comment]
Ah, yes.  You're correct.  I quickly added this after I asked Kyle to remove the delete link from his branch.  Forgot we will probably archive them.  I'll change the issue to archive instead of delete and will remove it from the backlog until we can discuss how we want to handle that.
