### ISSUE TITLE
Get video player working in all browsers

### ISSUE THREAD

**Issue by hortongn** [uclibs/ucrate#351]
### Descriptive summary

When a video is ingested into Scholar, ffmpeg creates a derivative that can be played on the work show page via the HTML5 video player.

See an example at
https://scholar.uc.edu/concern/media/rn301200z

Test the player in as many browsers possible on as many platforms possible (Mac, Windows, Linux, Android, iOS, etc).  For browsers where it's broken, either fix it or open a new issue.

**The player is definitely not working correctly in Safari on Mac.**  

The player code produced by Scholar for the work above is 
```
<video controls="controls" class="img-responsive video-js vjs-default-skin" data-setup="{}" preload="auto" >
    <source src="https://scholar.uc.edu/downloads/sx61dm98k?file=webm&amp;locale=en" type="video/webm" />
    <source src="https://scholar.uc.edu/downloads/sx61dm98k?file=mp4&amp;locale=en" type="video/mp4" />
    Your browser does not support the video tag.
</video>
```

It seems like it works in Safari if a 3rd `<source>` line without a `type` attribute is added.  However, I don't know if that breaks anything in other browsers.
```
<video controls="controls" class="img-responsive video-js vjs-default-skin" data-setup="{}" preload="auto" >
    <source src="https://scholar.uc.edu/downloads/sx61dm98k?file=webm&amp;locale=en" type="video/webm" />
    <source src="https://scholar.uc.edu/downloads/sx61dm98k?file=mp4&amp;locale=en" type="video/mp4" />
    <source src="https://scholar.uc.edu/downloads/sx61dm98k" />
    Your browser does not support the video tag.
</video>
```

You should be able to put the code above in a local .html file and open it in different browsers on your machine to test different incantations of the HTML.  We can also put some tests up on curly.libraries.uc.edu to make it easy to test changes on different machines.  Ask other people to try it if needed.

We may also need to set `height` and `width` attributes if the player doesn't show with the proper dimensions.

**Comment by bsp3ars** [comment]
After implementing the solution given above, I was able to successfully resolve the issue where the video would not start on Safari. However that solution led to diagnosing a second problem where the video file format is not accepted by Microsoft Edge browsers. It is currently believed that the solution is to reconfigure the system making the video derivatives to output mp4 files with the proper codecs.

**Comment by crowesn** [comment]
Might be worth testing this in nurax and sharing with samvera.
