### ISSUE TITLE
Work transfer does not reset edit rights on attached file_sets

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/ucrate#362]
### Descriptive summary

Work transfer does not reset edit rights on attached file_sets when the receiving user opts to remove depositor access.

### Expected behavior

When transferring a work, the receiving user can choose to remove access original depositor. When they do this the original depositor should not be able to edit the work or the attached file_sets.

### Actual behavior

When the receiving user chooses to remove access from the original depositor, the original depositor is still listed as an edit user of attached file_sets.

### Steps to reproduce the behavior

1. Create a work with a file
1. Transfer it to another user
1. As the other user, accept the request, removing depositor access
1. Check the edit_users on the attached file_sets

### Related work

See this class:

https://github.com/samvera/hyrax/blob/master/app/services/hyrax/change_content_depositor_service.rb

Should this be in the `work.file_sets.each` block?:

```ruby
f.apply_depositor_metadata(user)
f.permissions = [] if reset
f.save!
```

Note that this is an issue in Hyrax - we should open an issue there an contribute a fix.

**Comment by crowesn** [comment]
It looks like this default behavior in hyrax is intentional.

https://github.com/samvera/hyrax/blob/master/app/services/hyrax/change_content_depositor_service.rb

https://github.com/samvera/hyrax/blob/2.0-stable/spec/services/hyrax/change_content_depositor_service_spec.rb#L46
