### ISSUE TITLE
Research Hyrax 2.2.1 update

### ISSUE THREAD

**Issue by hortongn** [uclibs/ucrate#363]
### Descriptive summary

We need to decide if we should update to Hyrax ~~2.2.0~~ 2.2.1.
https://github.com/samvera/hyrax/releases/tag/v2.2.1
https://github.com/samvera/hyrax/releases/tag/v2.2.0

First steps:
1. Update app to use Hyrax 2.2.1
1. Run the tests and note what fails
1. Discuss with team how much work it will be to upgrade

**Comment by hortongn** [comment]
@bsp3ars I updated this issue.  Hyrax 2.2.1 is out now.

**Comment by bsp3ars** [comment]
After running the update, there was only 1 failure.
```
collection collection show page adding existing works to a collection preselects the collection we are adding works to and adds the selected works
     Failure/Error: first('input#check_all').click
     
     NoMethodError:
       undefined method `click' for nil:NilClass
```
And after checking hyrax for the comparison between  <a href="https://github.com/samvera/hyrax/compare/v2.1.0...v2.2.1">2.1.0 and 2.2.1</a>, I don't see why this can't be accomplished in a relatively short amount of time.
