### ISSUE TITLE
Research browser form autocomplete feature

### ISSUE THREAD

**Issue by hortongn** [uclibs/ucrate#367]
### Descriptive summary

Some web browsers like Firefox will offer suggestions when filling out a form based on past content the user has entered into form fields.  It seems to be flakey in UCrate and often doesn't offer suggesting for new work fields.

Research if there are ways HTML forms can be configured to work better with autocomplete.  If we can do anything to make form fields in UCrate offer suggestions, we do it.

**Comment by bsp3ars** [comment]
Recommended autocomplete fields:
1. Advisor
1. Author
1. Creator
1. College
1. Program or Department

To use the autocomplete feature in web browsers, you add the ```autocomplete = "value"``` attribute to the input field of your choice. As far as the values go, here is a good listing of all the supported values in <a href = "https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete">Firefox</a>. So far we only have the autocomplete attribute on the login page, so for other pages it depends on the browser to decide whether it will work or not.

**Comment by hortongn** [comment]
@bsp3ars In addition to the fields you already have, I would add autocomplete to
* publisher
* subject
* geo subject
* time period
* language
