### ISSUE TITLE
Revisit batch edit to resolve the difficult metadata fields

### ISSUE THREAD

**Issue by scherztc** [uclibs/ucrate#383]
### Descriptive summary

There are a few metadata fields in our application that do not work in the batch edit.  The primary reason for them not working is that the singular fields and hyrax 2 assumes all metadata fields are repeatable.

  Add College
  Add Program / Department
  Add Description
  Add Date Created
  Add Alternate Title
  Add Geo Subject
  Add Note
  Add License

### Expected behavior

That all of these fields display something and then saving values during batch edit.

**Comment by hortongn** [comment]
One change we considered is removing the description field from batch edit.  There is concern that it's too easy for users to accidentally wipe out their existing descriptions when they edit multiple works at once.

We should get the opinions of the product owners.
