### ISSUE TITLE
Update the Spanish and Mandarin translations

### ISSUE THREAD

**Issue by hortongn** [uclibs/ucrate#390]
### Descriptive summary

Note: Don't begin working on this issue until we are closer to release.  We will update all of the translations at once.

We should make sure that `config/locales/hyrax.es.yml` and `config/locales/hyrax.es.yml` contain the translated text for all of the entries in `config/locales/hyrax.en.yml`

Each work type also has it's own .es.yml and .zh.yml files that may need translations added.

Also browse through the application in Spanish and Mandarin mode and locate any other parts of the interface that are not translated.

**Comment by scherztc** [comment]
Mandarin is complete, but we still need to finalize Spanish.
