### ISSUE TITLE
Change remaining "ucrate" references to "Scholar@UC"

### ISSUE THREAD

**Issue by hortongn** [uclibs/ucrate#394]
### Descriptive summary

The files listed below still contain some reference to "ucrate."  They should be updated to use "Scholar@UC" or "scholar" as appropriate.  When possible, we should refactor the mailers and views to use i18n so that strings like this are not hard-coded.

- [x] app/views/static/student_instructions.html.erb
- [x] ~~app/views/hyrax/content_blocks/_form.html.erb~~
- [x] ~~app/views/static/_about_text.html.erb~~
- [x] app/mailers/embargo_mailer.rb
- [x] app/mailers/welcome_mailer.rb
- [x] app/mailers/change_manager/scholar_notification_mailer.rb
- [x] app/views/shared/_footer.html.erb
- [x] app/views/layouts/application.html.erb
- [x] app/views/static/login.html.erb
- [x] app/views/welcome_page/_student_welcome_text.erb
- [x] app/views/welcome_page/_welcome_text.html.erb
- [x] app/views/welcome_mailer/welcome_email_student.text.erb
- [x] app/views/welcome_mailer/welcome_email.html.erb
- [x] app/views/welcome_mailer/welcome_email.text.erb
- [x] app/views/welcome_mailer/welcome_email_student.html.erb
- [x] app/views/embargo_mailer/notify.html.erb
- [x] config/blacklight.yml
- [x] config/solr.yml
- [x] config/environments/production.rb
- [x] config/application.rb
- [x] config/recaptcha.yml
- [x] config/initializers/session_store.rb
- [x] README.md
- [x] spec/mailers/embargo_mailer_spec.rb
- [x] spec/features/welcome_mailer_spec.rb
- [x] spec/helpers/show_welcome_helper_spec.rb

**Comment by crowesn** [comment]
@hortongn
1. Should we change system variable names that refer to ucrate? Like solr cores with ucrate in the name? Should I change the application name?
1. There are some links to the repo i.e https://github.com/uclibs/ucrate - Are we going to change the name of the repo or merge in the scholar repo at some point?

**Comment by hortongn** [comment]
Good questions

I think we should probably change the ucrate references in the solr.yml and blacklight.yml back to the original `hydra-development`.  I probably should have never customized that.  Update the README accordingly.

I think variables should be changed to scholar as well unless it causes us a lot of grief.

Any links to the GitHub repo should stay ucrate for now.  I'm not sure if we will eventually change the repo name, but for now we will keep it `ucrate`.
