### ISSUE TITLE
Tweak note line on create batch form

### ISSUE THREAD

**Issue by hortongn** [uclibs/ucrate#397]
### Descriptive summary

The create batch form has a line at the top of the page that needs to be tweaked to match Scholar.

The line currently says "To create a single work for all the files, go to Add New Work"

It should instead say "Note: To create a single work for all the files, go to the Add New Generic Work page."  The "Generic Work" part should be whatever type of batch is currently being created.

This is how the line is currently generated in Scholar:
https://github.com/uclibs/scholar_uc/blob/develop/app/views/hyrax/batch_uploads/_form.html.erb#L8

![new works by batch scholar uc](https://user-images.githubusercontent.com/5639859/45451647-ac39d680-b6a9-11e8-9ed2-ba053d827a00.png)

**Comment by crowesn** [comment]
@hortongn Since we want the worktype to be dynamic, I think this is going to require a view partial override - just want to make sure this is cool before continuing.

**Comment by hortongn** [comment]
Yes, I agree that we will need to override a partial.  But it would be nice if we could move the note line in that partial to the locales so it will be translated when needed.  Not sure how easy that will be with the dynamic work type in that line.
