### ISSUE TITLE
Update the collection form to match Scholar

### ISSUE THREAD

**Issue by hortongn** [uclibs/ucrate#399]
### Descriptive summary

The new collection form needs changes so that the fields match up with the collection form in Scholar.

Scholar has the following fields on the collection form (all required)
* Title (single value)
* Creator (multiple value)
* Description (single value)
* Rights (which we are calling License in ucrate)

Those should be the only fields available on the form.  No `Additional fields` button.  (We may eventually want additional metadata fields on the collection form, but that's a future issue.)

Note: collection avatar and visibility are handled on other tabs and not part of this issue.

~~It also appears that the selected license is not being remembered when the collection is edited.  Editing a collection will display a form that looks like a license was never chosen.  That bug should be fixed as part if this issue.~~ See #438

**Comment by bsp3ars** [comment]
I am making the license not being remembered a different issue, since it will delay the fix for the collection form.
