### ISSUE TITLE
Implement statistics changes from Scholar

### ISSUE THREAD

**Issue by hortongn** [uclibs/ucrate#413]
### Descriptive summary

We made several tweaks to scholar_uc to get statistics working for us.  So we need to...
1. Figure out what tweaks are still needed when using Hyrax 2.x
1. Implement those tweaks

The latest changes in scholar_uc to implement this can be seen here:
https://github.com/uclibs/scholar_uc/compare/1c59a0a3f57837308d1c755936691e0e52441594...0618cf55d046d869e73533ab4f70c8c306786bcd

A good first step is to bring over all those changes and get the specs passing.  We will then need to try testing it on scholar-qa.uc.edu

**Comment by hortongn** [comment]
@scherztc As part of this issue, we need to uncomment and add an environment variable for the setting that turns analytics on and off:
https://github.com/uclibs/ucrate/blob/develop/config/initializers/hyrax.rb#L52

maybe something like `config.analytics = ENV["SCHOLAR_ANALYTICS_TOGGLE"]` and then add that value to `.env.development` and `.env.test` (`false` in both cases)

**Comment by scherztc** [comment]
https://github.com/uclibs/scholar_uc/pull/1646

**Comment by scherztc** [comment]
https://github.com/uclibs/scholar_uc/wiki/Adding-Google-Analytics-in-Scholar

**Comment by scherztc** [comment]
Start Date October 26, 2018
