### ISSUE TITLE
Test the application on mobile device

### ISSUE THREAD

**Issue by hortongn** [uclibs/ucrate#432]
### Descriptive summary

scholar.uc.edu currently has a responsive design that adapts the layout for mobile devices or very narrow browser windows.  We need to verify that ucrate behaves the same way.

Navigate http://curly.libraries.uc.edu:3002 on a mobile device or narrow browser window and note any places where the layout doesn't match Scholar or where features don't work.

This issue can be closed once any inconsistencies/problems have been fixed.

**Comment by bsp3ars** [comment]
Notes on changes:
Main Page
1. Scholar@UC Title is off centered
1. The sub navigation looks bad

Browse Page
1. Nav bar splits on scholar weirdly
1. The sub navigation looks bad

Contribute Page
1. Nav bar splits on scholar weirdly
1. The sub navigation looks bad
1. Buttons can overlap the works text
1. Work box groups are not aligned properly

Add New Page
1. Hamburger menu opens automaticaly
1. No license wizard
1. Tabs don't resize

Dashboard
1. Profile page is garbage
1. Auto-hide hamburger menu

**Comment by crowesn** [comment]
@bsp3ars @hortongn The hidden license wizard on mobile res is intentional - the widget is not responsive and causes problems at mobile res so we opted to hide the button below a threshold.
