### ISSUE TITLE
Sort collections first on catalog index page

### ISSUE THREAD

**Issue by hortongn** [uclibs/ucrate#434]
### Descriptive summary

When viewing `/catalog` on production Scholar, collections are displayed before any works.  We want that same behavior in ucrate.

Here is where the change was made in Scholar
https://github.com/uclibs/scholar_uc/blob/develop/solr/config/solrconfig.xml#L113-L115

No test is needed for this, but to try it in your own environment you will need to copy your updated `solr/conf/solrconfig.xml` into your local solr_wrapper instance.

**Comment by crowesn** [comment]
@hortongn I think @changy66 already took care of this: https://github.com/uclibs/ucrate/commit/fedf77164ad42e97b3dae44f2b0d7aa9e910ba40

**Comment by hortongn** [comment]
@crowesn Thanks.  Don't know why I missed that when I searched the solrconfig
