### ISSUE TITLE
Collections facet is not displaying

### ISSUE THREAD

**Issue by hortongn** [uclibs/ucrate#437]
### Descriptive summary

Hyrax 2.x added a "Collections" facet that displays at the bottom of all the facets on the catalog page.  For some reason it is not displaying in ucrate.

The line in CatalogController is still there, but it's not working from some reason:
https://github.com/uclibs/ucrate/blob/develop/app/controllers/catalog_controller.rb#L56

We may have a problem with the `member_of_collection_ids` Solr tag.  Something might have been missed when we upgraded Hyrax versions.

You can see a working version of this facet on Nurax:
https://nurax-dev.curationexperts.com/catalog

**Comment by crowesn** [comment]
@hortongn I'm unable to recreate the bug:

### Steps
1. Created a collection
1. Set collection visibility to open access 
1. Added open access work

<img width="403" alt="screen shot 2018-10-02 at 1 47 18 pm" src="https://user-images.githubusercontent.com/1069588/46366748-edd6f500-c649-11e8-947d-ef747567c97b.png">

**Comment by hortongn** [comment]
Weird.  Wonder why it wasn't showing for me locally or on curly.  I do see the facet now locally.  Maybe it was missing on curly because the collections there don't have works in them.
