### ISSUE TITLE
Emails are not being sent on removal for proxy and editor

### ISSUE THREAD

**Issue by bsp3ars** [uclibs/ucrate#450]
While I was implementing the Change Manager created by Kyle Lawhorn, I noticed that emails were not being sent when you remove someone as a Proxy, or when you remove them as an editor. After consulting @hortongn about the issue, we checked and the issue is affecting production Scholar as well. 

~~Check with @hortongn about whether we still want an email for both proxy removal and editor removal.~~  We do want this.  Now that UCrate is in production, we should test on scholar.uc.edu to see what emails are not happening and fix it.

**Comment by scherztc** [comment]
I did receive the following email from curly when I removed my proxy.

Dear Thomas Scherz:

Amy Scherz has removed you as a proxy in Scholar@UC. A proxy can create and upload files on behalf of another user as well as edit, or delete those corresponding works and files. If you feel that this was made in error, Scholar@UC team.
Thanks, Scholar@UC
