### ISSUE TITLE
Run fixity checks on production

### ISSUE THREAD

**Issue by hortongn** [uclibs/ucrate#451]
### Descriptive summary

This is what we need to do to run fixity checks on content:
https://github.com/samvera/hyrax/wiki/Hyrax-Management-Guide#fixity-checking

We should run this manually before releasing Scholar 4.0 and then possibly schedule it to run periodically.

Of course, testing this on scholar-dev first is recommended.

**Comment by crowesn** [comment]
https://bibwild.wordpress.com/2017/05/01/exploring-and-planning-with-sufiahyraxfedora-fixity-validation/
