### ISSUE TITLE
Remove Search Scholar@UC label

### ISSUE THREAD

**Issue by bsp3ars** [uclibs/ucrate#468]
After reviewing the 2.3.3 update from hyrax, it was noticed that they added a label to help with accessibility. However the label is unnecessary for us, and caused a visibility issue. We have removed it from the browse page for another accessibility scan, however it may cause other issues. I know that it is on the "My Works" page, however it could also be on other pages.

**Comment by hortongn** [comment]
@bsp3ars Did the accessibility scan complain about the search label being removed?  If not, I think we can move ahead with removing it from our code.
