### ISSUE TITLE
Files created by proxies don't give edit access to owners

### ISSUE THREAD

**Issue by hortongn** [uclibs/ucrate#488]
### Descriptive summary

If I'm a proxy and create a work with some files attached on behalf of another user (the owner), that owner will have edit access to the work, but not to the files.

The owner should be able to edit any file sets created by their proxies.

This is probably a bug in our app where we broke it somewhere, but we should verify that Hyrax doesn't have the bug.  You can test at https://nurax-dev.curationexperts.com

### Steps to reproduce the behavior

1. Create a work with file(s) as a proxy
1. Log in as the owner
1. Visit the show page for one of the files
1. Notice that you don't have an edit button

**Comment by crowesn** [comment]
@hortongn 
On what env was this encountered? I can't recreate the bug on nurax __or local/dev__.

<img width="1328" alt="screen shot 2018-11-06 at 10 11 00 am" src="https://user-images.githubusercontent.com/1069588/48073260-5fa3e080-e1ac-11e8-91fb-f1396e75919d.png">

**Comment by hortongn** [comment]
Hmm.  I was running the app locally.  I will try it again and report back here.  We're you running :inline or :sidekiq?

**Comment by hortongn** [comment]
@crowesn OK, I just did some more testing in my local environment and confirmed this:

Inline jobs: A user with a work created by a proxy DOES have edit access to attached files.

Sidekiq jobs: A user with a work created by a proxy DOES NOT have edit access to attached files.

So the problem exists for me when using sidekiq.  See if you can replicate that behavior in your environment.

**Comment by crowesn** [comment]
lol https://github.com/samvera/hyrax/commit/6a4d32ecd395aa5a36b1804ffd8d6b7750cea616

**Comment by crowesn** [comment]
https://github.com/samvera/hyrax/pull/3080

**Comment by crowesn** [comment]
Created issue for this on hyrax. https://github.com/samvera/hyrax/issues/3416

**Comment by scherztc** [comment]
We need to check with the community to see if they are intending to solve this with 3.0 release.

**Comment by scherztc** [comment]
This might help : https://github.com/uclibs/scholar_uc/pull/1328/files

**Comment by scherztc** [comment]
https://github.com/samvera/hyrax/commit/90f7a9f0593e7c44bfbbe4a4cf4f446f9636a5f7#diff-542d307457b483902c56ac6c42e21456
