### ISSUE TITLE
Test the application in production mode

### ISSUE THREAD

**Issue by hortongn** [uclibs/ucrate#493]
### Descriptive summary

Depends on #491 being merged

We should make sure that the application starts and works correctly in production mode so that we are not surprised by anything when we deploy for the first time to scholar-qa.uc.edu

**Comment by hortongn** [comment]
We will need to `bundle install --without development test` in production mode or the spring gem will cause us problems.

@crowesn if you come across any other useful details about getting the app running in production, please comment here.

**Comment by crowesn** [comment]
Notes from running in production on local
* Threw an error asking that this line be un-commented to set the secret key https://github.com/uclibs/ucrate/blob/develop/config/initializers/devise.rb#L21
* Be sure to set proper urls/ports in `config/solr.yml`, `config/fedora.yml`, and `config/blacklight.yml`

**Comment by hortongn** [comment]
Closing this.  If there are any other problems with production mode we will see them when we deploy to scholar-qa
