### ISSUE TITLE
Generate SHA-256 and MD5 checksums for all files

### ISSUE THREAD

**Issue by hortongn** [uclibs/ucrate#55]
### Descriptive summary

The application should be configured to generate both SHA-256 and MD5 checksums for ingested files.  The checksums should be exposed on the file show page.

Fedora configuration is likely needed:
https://wiki.duraspace.org/display/FEDORA4x/Fixity+Checking

Trello: https://trello.com/c/QVrDoJ0h/36-generate-checksum

### Expected behavior

When a file is ingested, the SHA-256 and MD5 checksums are stored in Fedora.  They are also displayed to users on the file show page.

**Comment by scherztc** [comment]
https://bibwild.wordpress.com/2017/05/01/exploring-and-planning-with-sufiahyraxfedora-fixity-validation/

**Comment by jayanthdeejay** [comment]
https://github.com/uclibs/scholar_uc/wiki/Checksum,-characterization-and-fixity-checks
@hortongn I am still trying to understand FITS and characterizations.

**Comment by jayanthdeejay** [comment]
<img width="1006" alt="screen shot 2018-04-04 at 2 01 53 pm" src="https://user-images.githubusercontent.com/2188493/38325806-1278c882-3812-11e8-8618-6ae5ed3f1be0.png">

**Comment by jayanthdeejay** [comment]
Please go through the updated wiki page commented above. I'm closing this issue.

**Comment by jayanthdeejay** [comment]
https://github.com/samvera/hyrax/issues/1079
