### ISSUE TITLE
Scan uploaded files for malware before ingest

### ISSUE THREAD

**Issue by hortongn** [uclibs/ucrate#56]
### Descriptive summary

When a user uploads a file and saves the work, all files should be scanned for viruses.  If a virus is found, it should not be attached to the work and the user should be notified.

This feature can be implemented the way as it's done on Scholar@UC:
https://github.com/uclibs/scholar_uc/commit/8161ecfdb278b91c93390ca74c38680f288f3496

Trello: https://trello.com/c/QFKaKwJD/6-virus-screening-of-deposited-files

**Comment by jamesvanmil** [comment]
https://github.com/samvera/hyrax/wiki/Hyrax-Management-Guide#virus-checking

**Comment by crowesn** [comment]
https://github.com/samvera/hyrax/issues/2284#issuecomment-362396437
