### ISSUE TITLE
Commit fixes for the security scan

### ISSUE THREAD

**Issue by hortongn** [uclibs/ucrate#585]
### Descriptive summary

We are making changes directly on scholar-qa to satisfy the security scan (issue #502), but this is a reminder for us to make sure we commit those changes to the repo as well once we know what the changes should be.

Note: if we need to set options only for production, we can use `Rails.env.production?`.  E.g. `Rails.application.config.session_store :cookie_store, key: '_scholar_uc_session', secure: Rails.env.production?`

**Comment by hortongn** [comment]
@scherztc We need to figure out how to set a secure attribute on this cookie: 
https://github.com/uclibs/ucrate/blob/develop/app/controllers/callbacks_controller.rb#L38

**Comment by scherztc** [comment]
This should do it : https://github.com/uclibs/ucrate/blob/7f9beb00a236210a6743e189e53c899393b14001/config/initializers/devise.rb#L168

**Comment by scherztc** [comment]
https://github.com/uclibs/ucrate/blob/develop/config/environments/production.rb#L45
