### ISSUE TITLE
Enhance the collection exports feature

### ISSUE THREAD

**Issue by hortongn** [uclibs/ucrate#588]
### Descriptive summary

We need to fix and enhance various parts of the Collection Export feature:

* Re-enable the collection export buttons that were disabled in #586 

* Add the remaining work types and fields to `config/metadata_export_map.yml` (Test with all work types.  Note any problems with certain fields like multi-value fields, etc.)

* Collection Exports page (`/collection_exports`)

    * Fix the column headers.  The `Delete` and `File` headers are mixed up

    * Display timestamps in our current timezone instead of UTC

    * Instead of displaying the CSV data when the user clicks `Download`, download the file to their browser.

    * Change the route for Collection Exports from `/collection_exports` to `/dashboard/collection_exports`

* Verify that the downloaded .csv file can be properly loaded into a spreadsheet.  The file is actually tab delimited instead of comma delimited.  It may make more sense to name the files .tsv instead.

* Uncomment the section on the What's New page for Collection Exports.  Update the text as needed.

* The export fails for collections with sub-collections or nested works in them.  Sub-collections and nested works should be included in the same .csv file.  We probably want a "parent_id" column in the CSV file that indicates the parent collection ID.  Check with Glen when you are ready to attack this feature so we can set clear expectations for how it will work.

Previous work:
* https://github.com/uclibs/ucrate/pull/109
* https://github.com/uclibs/ucrate/pull/144

**Comment by chuckgreenman** [comment]
Also noticed that translation for collection_export.title is missing, will add that.
