### ISSUE TITLE
Use Datacite for DOIs

### ISSUE THREAD

**Issue by hortongn** [uclibs/ucrate#599]
### Descriptive summary

The DOI feature needs to be updated to use Datacite as a provide instead of EZID.

The first step for this task is to review the approach that has been discussed in the past.  See @hortongn 

Existing DOIs will need to be migrated to Datacite as well.  That needs to be done at the same time this enhancement is deployed.

**Comment by hortongn** [comment]
### Some notes on this issue:

James has credentials for Datacite

James has a `datacite` branch on our hydra_remote_identifers fork:
https://github.com/uclibs/hydra-remote_identifier/tree/datacite

Samvera EZID to DataCite DOI Working Group:
https://wiki.duraspace.org/display/samvera/Samvera+EZID+to+DataCite+DOI+Working+Group

Datacite only supports XML, but our current hydra_remote_identifiers gem only supports key data pairs.  

When Notre Dame switched to Datacite (see https://github.com/ndlib/curate_nd/commit/fc33304e141002517fb6ccfebb605a9f0b7a0678), they stopped using hydra_remote_identifiers and switched to Duke's ezid-client (https://github.com/duke-libraries/ezid-client)

We can move forward with our existing code and just update hydra_remote_identifiers:
* change data_for_request to use XML
* we can test this change in localhost
* there's a bug with ldp-create
* some styling issues need to be tweaked
* James can advise as a SME

**Comment by scherztc** [comment]
- [ ] Question:  Hydra-remote-identifier vs Duke ezID client?
- [ ] Get credentials TEST/PROD from Datacite
- [ ] Build some sort of DataCite DOI service
        change data_for_request to use XML
        there's a bug with ldp-create
- [ ] Test service in HRI or Duke exID
- [ ] Integrate DataCite DOI service into UCRATE application
        some styling issues need to be tweaked
        YML
         Initiliazers
         Bamboo / ENV variables
- [ ] Test service integration in application
- [ ] Deploy to DEV
- [ ] Deploy to QA
- [ ] Deploy to PROD
- [ ] Rake task for current work migration / clean up

**Comment by hortongn** [comment]
@chuckgreenman @scherztc 

I'm moving issue https://github.com/uclibs/scholar_uc_legacy/issues/1834 to here since it's something that should be verified as part of the Datacite switchover.

That issue calls for us to verify that all the needed create/update/delete tasks for DOIs are being properly handled:
* minting a DOI
* reserving a DOI on a private or embargoed work
* changing status of DOI from reserved to public when a private or embargoed work become public.
* updating information in the EZID system if core metadata reported to that system changes (e.g. the work's title, etc.).
* generating tombstone in EZID system if a work with a DOI is deleted.

You guys should 1) verify all those things work properly now in production Scholar and 2) verify they still work after our Datacite migration.

I can show you how to log into our EZID account to verify those things.

**Comment by hortongn** [comment]
@chuckgreenman @scherztc 

I'm closing https://github.com/uclibs/scholar_uc_legacy/issues/130 and you should consider looking into this issue as part of the Datacite changes.  EZID supports a "resource type" field that we are not currently setting when a DOI is minted.  Works in Scholar have a resource_type in their models, but we don't expose it to the work form.  We should ask James if resource type is something we should worry about moving forward.

![ezid](https://user-images.githubusercontent.com/5639859/54783553-0dfa7080-4bf8-11e9-8c0e-ef89f4b05de3.png)

**Comment by hortongn** [comment]
@chuckgreenman @scherztc 

In today's webinar, Britta recommended 2 changes to the DOI links we display on work show pages:
* Remove the "dx." part of the URL
* Use https

E.g. use `https://doi.org/doi:10.7945/C2NP4P` instead of `http://dx.doi.org/doi:10.7945/C2NP4P`

I *think* we need to make that change here: https://github.com/uclibs/hydra-remote_identifier/blob/setting-status/lib/hydra/remote_identifier/remote_services/doi.rb#L83

See https://support.datacite.org/docs/datacite-doi-display-guidelines for more details.

Again, feel free to start breaking this stuff into multiple issues if you want.  Maybe create a `Datacite` tag in GitHub to keep track of all the pieces.

**Comment by scherztc** [comment]
Feature Test


Feature | Scholar Response | Action | Sub-Action | EZID Status | Landing Page
-- | -- | -- | -- | -- | --
  |   |   |   |   |  
Private Work | Created w/o DOI | EDIT Later | MINT ONE | reserved | http://dx.doi.org/doi:10.7945/C28H7P   DOI NOT FOUND
Private Work | Created w/o DOI | EDIT Later | ALREADY HAVE ONE | public    reserved   unavailable | Checks for   validationin form
Private Work | Removed | Tombstone | Status? | unavailable | https://ezid.cdlib.org/tombstone/id/doi:10.7945/C2J112
Private Work | Created w DOI |   | MINT ONE | reserved | http://dx.doi.org/doi:10.7945/C28H7P   DOI NOT FOUND
Private Work | Created w DOI |   | ALREADY HAVE ONE | public   reserved   unavailable | Checks for validation   in form
Private Work | w DOI | SET to PUBLIC |   | reserved   public | DOI NOT FOUND   https://scholar.uc.edu/concern/media/p5547s82j?locale=en
Embargo Work | w DOI | RELEASED |   | reserved | DOI NOT FOUND
Public Work | Created w/o DOI | EDIT Later | MINT ONE | public | https://scholar.uc.edu/show/bc386k690   http://dx.doi.org/doi:10.7945/C2J112
Public Work | Created w/o DOI | EDIT Later | ALREADY HAVE ONE | public   reserved   unavailable | Checks for validation
Public Work | Removed |   | Broken URL in EZID : https://scholar.uc.edu/show/bc386k690 | unavailable | Whoops! Page Not Found   https://ezid.cdlib.org/tombstone/id/doi:10.7945/C2J112
Public Work | Created w DOI |   | MINT ONE | public | https://scholar.uc.edu/concern/media/47429b29w
Public Work | Created w DOI |   | ALREADY HAVE ONE | public   reserved   unavailable | Checks for validation
Univesity Work | Created w DOI |   | MINT ONE | reserved | DOI NOT FOUND

**Comment by scherztc** [comment]
The Embargo test did NOT take the work out of reserved status on the release date.  

https://scholar.uc.edu/concern/media/5h73px13f?locale=en
