### ISSUE TITLE
Configure IIIF photo viewer

### ISSUE THREAD

**Issue by hortongn** [uclibs/ucrate#60]
### Descriptive summary

Hyrax 2.x has a IIIF viewer built in, but it needs to be configured and tested.  

1. Test that all features and controls work as expected.

1. Research the options and set the appropriate settings (https://github.com/uclibs/ucrate/blob/develop/config/initializers/hyrax.rb#L132-L153).  Also compare settings in UCrate to this commit in Nurax: https://github.com/curationexperts/nurax/commit/572965dc1032162df2cf36161d4c3aea32c33576

1. Test with various image types.  Ex. jpg, gif, png, jp2, tiff.  You can trying getting some different images types from https://drc.libraries.uc.edu.  Also test that it behaves with a mix of images and non-images attached to a work.

1. Test that the viewer respects file permissions (private, etc.)

Trello: https://trello.com/c/CTl0bNuH/90-iiif-photo-viewer

**Comment by hortongn** [comment]
I added some additional things to check in the description above.

**Comment by jayanthdeejay** [comment]
Comments:
* Making a work private does not display the respective image in the image viewer (IV) but thumbnails are generated and are viewable.
* Changing the image visibility from private to public does let the IV to display the image as expected. IV settings work as expected.
* By changing a public image's visibility to private at a later stage, image viewer still displays the image as if it were a public image.
* IV does not render TIFF, PNG and GIF images.
* Application breaks when saving a work with JP2 image
