### ISSUE TITLE
Fix image for featured collection on scholar.uc.edu

### ISSUE THREAD

**Issue by hortongn** [uclibs/ucrate#616]
### Descriptive summary

The image for the featured collection on the home page of scholar.uc.edu is missing.  

We need to 
1. figure out why
1. restore the image

The current featured collection is https://scholar.uc.edu/collections/wm117q83p

**Comment by scherztc** [comment]
It looks like it displaying properly, now.  It might have been a cache problem.
Please confirm that you see the same thing at wrap up.

**Comment by scherztc** [comment]
Set featured collection thumbnail for home page with PUBLIC image.  Still need to refactor how the thumbnails get selected for that drop down on the EDIT page.(public/private and works within works)
