### ISSUE TITLE
Collections descriptions are not displaying on view or edit forms.

### ISSUE THREAD

**Issue by scherztc** [uclibs/ucrate#619]
### Descriptive summary

When viewing a collection, I do not see the description.  
When I edit my collection the description field is blank.

### Expected behavior

Description should be visible and editable.
 

### Actual behavior

The value of the description predicate in Fedora is not displaying in the application.

### Steps to reproduce the behavior

1. Confirm collection description is still in Fedora
1. Work through model mapping to discover what field the forms and presenters are using.

### Related work

Link to related issues or prior related work here.

**Comment by hortongn** [comment]
@scherztc Scholar Legacy uses `dc: description` for collections while ucrate uses `dcterms: description` for collections

So we need to get collections in ucrate to use `dc: description`

Related work https://github.com/uclibs/ucrate/pull/568

An alternative fix (if needed) would be for us to migrate all of the existing descriptions in Fedora to the new predicate.

**Comment by hortongn** [comment]
In the console, running `Collection.properties["description"].predicate` returns
`#<RDF::Vocabulary::Term:0x22d2bf0 ID:http://purl.org/dc/terms/description>`

We don't want `terms` in the predicate
