### ISSUE TITLE
Field labels are incorrect on some work show pages

### ISSUE THREAD

**Issue by hortongn** [uclibs/ucrate#653]
### Descriptive summary

Some fields have incorrect labels on the ETD show page.

### Steps to reproduce the behavior

1. Start a new ETD work
1. add content into the Degree Program field
1. add content into the Degree Date field
1. fill out the other required fields
1. Save the work

The show page will display
* the Degree Program field as "Department"
* the Degree Date field as "Date Created"

**Comment by hortongn** [comment]
I did not find any more incorrect labels on the other work types.

**Comment by crowesn** [comment]
Just wanted to confirm we're okay with the catalog view showing diff labels: 

<img width="600" alt="screen shot 2019-02-20 at 1 02 39 pm" src="https://user-images.githubusercontent.com/1069588/53113567-e4262f00-350f-11e9-9af5-fdf3dedfab11.png">

**Comment by hortongn** [comment]
Reopening this because it's not working correctly after it was merged into develop.  Something with fixing a merge conflict broke things.

This branch is the one that was merged and is broken:
`bug/#653-Field-labels-are-incorrect`

This branch is the original one from Chuck that works:
`bug/#653-Field-labels-are-incorrect-redux`

**Comment by hortongn** [comment]
@chuckgreenman I suggest playing with the ordering of the lines in app/views/hyrax/base/_attribute_rows.html.erb to see if that somehow affects your ETD label changes.

**Comment by hortongn** [comment]
Closing because this tested properly on scholar-qa.  There's a change that a Solr reindex will be needed on production to make the labels show properly.
