### ISSUE TITLE
Clicking on "File Manager" button on work show page throws an error

### ISSUE THREAD

**Issue by hortongn** [uclibs/ucrate#668]
### Descriptive summary

Discovered this while running through the test script.

If you create a work with files attached, save the work, and then click the "File Manager" button, the error below is thrown.

![action controller exception caught](https://user-images.githubusercontent.com/5639859/53270697-710cec00-36ba-11e9-8c6f-bdedccd91b7b.png)

Looks like `@presenter` may be `nil` in this case and ruby doesn't like concatenating nil with strings.

It looks like this regression was introduced by https://github.com/uclibs/ucrate/pull/646

**Comment by crowesn** [comment]
https://github.com/uclibs/ucrate/blob/ef357ef407a6616d468ac7c4a044a20b0f9513d9/app/views/hyrax/base/_file_manager_member.erb#L9

typo: "loacle"
