### ISSUE TITLE
Generate a discoverable collection with DB:seed

### ISSUE THREAD

**Issue by scherztc** [uclibs/ucrate#680]
The collection that we built in the DB:seed works for holding items, but is not showing up in facets or as an option when using and Add to Collection button.  We need to improve the creation of this seed collection

**Comment by crowesn** [comment]
https://github.com/samvera/hyrax/blob/c871bed0285165fbe4654218dcc4fed78e9f0639/app/search_builders/hyrax/catalog_search_builder.rb#L27

**Comment by scherztc** [comment]
Try this on scholar-qa.uc.edu.  I ran the db:seed file and here are the test credentials.

Password for all accounts: jjXaoz59

Account created: manydeposits@example.com
Account created: nodeposits@example.com
Account created: delegate@example.com
Account created: admin@example.com

**Comment by bsp3ars** [comment]
Closing because we can't replicate
