### ISSUE TITLE
Display "Date Modified" & "Date Uploaded" on the work show page

### ISSUE THREAD

**Issue by hortongn** [uclibs/ucrate#683]
Moved from https://github.com/uclibs/scholar_uc_legacy/issues/1906

### Descriptive summary

Date Uploaded and Date Modified are showing in the Catalog Browse but not on the work show page. In the context of Hyrax 2.1, review with P.O.s where these system provided fields should display - on the Catalog Browse, and/or the Work Show page.

**Comment by bsp3ars** [comment]
After talking with @hortongn, it was decided that the issue needs to be tweaked to changing the work show page to show Date Uploaded and Date Modified, just like the browse page.
