### ISSUE TITLE
Contact form error message indicates a captcha error when problem is email

### ISSUE THREAD

**Issue by hortongn** [uclibs/ucrate#690]
### Descriptive summary

If a non-logged in user tries to submit the contact form with an invalid email address, the user is told that they must complete the captcha even if they have successfully done that.

### Steps to reproduce the behavior

1. Log out of Scholar
1. Submit the contact form with an invalid email address.

The error will say `Sorry, this message was not sent successfully. You must complete the Captcha to confirm the form. Email is invalid.`

Note how the actual error message (`Email is invalid`) is there, but the captcha message should not be.

**Comment by bsp3ars** [comment]
https://github.com/uclibs/ucrate/blob/develop/app/controllers/hyrax/contact_form_controller.rb
Change the error message to a method instead
