### ISSUE TITLE
Highlight search terms on catalog view page

### ISSUE THREAD

**Issue by hortongn** [uclibs/ucrate#705]
(moved from https://github.com/uclibs/scholar_uc_legacy/issues/222)

### Descriptive summary

When the user's search terms appear in the the search results, highlight them so the user can more easily see the matches.

Example: if the user searches for `library degree`, highlight any words in the search results that caused those records to be included.  See example below.

![highlight](https://user-images.githubusercontent.com/5639859/54495860-652dd780-48be-11e9-9867-65e418d4b770.png)

**Comment by bsp3ars** [comment]
Could potentially use the mark.js (https://markjs.io/) library to do this
