### ISSUE TITLE
Child works should link to their parent work

### ISSUE THREAD

**Issue by hortongn** [uclibs/ucrate#710]
### Descriptive summary

A user viewing the public show page for a child work has no way of knowing there is a parent work or how to get to it.

For child works, we should include a link to the parent under the Relationships section (the same section that shows what collections a work belongs to).

The parent work can be found using `work.member_of`

Example:

### Relationships
**In Collection:**
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Global Marine Biodiversity Archive
**Attached to Parent Work:**
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Link to Parent Work

![parent](https://user-images.githubusercontent.com/5639859/54718382-c0ff9700-4b30-11e9-9f90-2e7c0d6e04bf.png)

**Comment by scherztc** [comment]
@hortongn :  See https://github.com/samvera/hyrax/issues/2960

**Comment by scherztc** [comment]
https://cdr.lib.unc.edu/
