### ISSUE TITLE
Get fixity checks working and running regularly

### ISSUE THREAD

**Issue by hortongn** [uclibs/ucrate#727]
### Descriptive summary

Issue #451 identified problems with the fixity check service.  We really need to get it working properly for our needs so we can verify that all files are safe.

See #451 for what we know so far.  However, things may behave differently now under our current version of Hyrax.

All of our file set pages currently say "Fixity Check: Fixity checks have not yet been run on this object".  

After running this service locally, I see "Fixity Check: [passed] 1 File with 2 total versions checked 2019-04-05 10:00:45 -0400"

We need to
1. Get `Hyrax::RepositoryFixityCheckService.fixity_check_everything` to run without erroring
1. Have any emails it generates go to "scholar@uc.edu" instead of the file's owner.
1. Schedule the service to run regularly (monthly?)

Possibly relevant: https://github.com/samvera/hyrax/issues/3000

**Comment by scherztc** [comment]
Key components of the Fixity Check Process:

file_set = ::FileSet.find(file_set.id)
::Hyrax::RepositoryFixityCheckService.fixity_check_everything (All)
::Hyrax::FileSetFixityCheckService.new(file_set).fixity_check (Individual)
::Hyrax::VersioningService.latest_version_of(file_set.original_file).uri (URI for latest version of file)
ChecksumAuditLog.latest_for_file_set_id(file_set.id) (Review Post Check Audit log)
::Hyrax::FixityStatusService.new(file_set.id) (Check Pass/Fail Status)
::Hyrax::FixityStatusPresenter.new(id).render_file_set_status (Renders display message)
::Hyrax::FixityCheckFailureService.new(file_set, checksum_audit_log: checksum_audit_log) (Starts the Failure communication)
ActiveFedora::FixityService.new(uri).check (What actually does the check)
ActiveFedora::FixityService.new(uri).expected_message_digest (Retrieves SHA from Fedora)
