### ISSUE TITLE
Switch from Travis to CircleCI

### ISSUE THREAD

**Issue by hortongn** [uclibs/ucrate#739]
### Descriptive summary

The Samvera community is moving their repos from Travis to CircleCI.  We should research service and switch Scholar to it.

We only want to switch right now if we can use CircleCI with Scholar for free.

There are many examples of other repos switching to CircleCI:
* https://github.com/samvera/solrizer/commit/fad269d496605082c6e4bbc0b1080ad25facad04
* https://github.com/samvera/ldp/commit/14630f508294e4c9522bb7170a299f88d5713d07#diff-1d37e48f9ceff6d8030570cd36286a61
* https://github.com/samvera/hydra-pcdm/commit/fff8a8d594e121aa068da0455a981b1d2a89d5c8
* https://github.com/samvera/hyrax/commit/408f95ea3baeca39f5178664185caf4ba12de525#diff-1d37e48f9ceff6d8030570cd36286a61

Look into Samvera's CircleCI Orb (See some of the commits above)

Recording of Travis to CircleCI discussion (for Hyku):
https://iu.mediaspace.kaltura.com/media/CircleCI+knowledge+share+and+Hyku+swarm+-+May+2nd%2C+2019/0_bzw7tbz2

**Comment by scherztc** [comment]
Samveras CirclCi Orb : https://circleci.com/orbs/registry/orb/samvera/circleci-orb

**Comment by scherztc** [comment]
https://github.com/samvera-labs/samvera-circleci-orb

**Comment by scherztc** [comment]
This job has been blocked because resource-class:large is not available on your plan. Please upgrade to continue building.
