### ISSUE TITLE
DOI intentifer_url fields still have EZID domains

### ISSUE THREAD

**Issue by hortongn** [uclibs/ucrate#755]
### Descriptive summary

`work.identifier_url` for works that had DOIs before our migration still have EZID domains in them.  Example:
`https://ezid.cdlib.org/id/doi:10.7945/C2R11X`

Those fields should be modified to use
`https://api.datacite.org/dois/10.7945/C2R11X`

The incorrect URL is preventing users from editing their existing works with DOIs.

**Comment by scherztc** [comment]
We reset the identifier_url on 638 works.
