### ISSUE TITLE
Allow users to batch edit works in a collection

### ISSUE THREAD

**Issue by hortongn** [uclibs/ucrate#76]
### Descriptive summary

A user should be able to use Hyrax's batch edit functionality to edit metadata of all works in a collection.  

Users currently need to select individual works they want to batch edit.  Add the ability to select all of the works based on the collection they're in.

Trello: https://trello.com/c/eMIIyBWu/50-add-collection-level-metadata-to-records

**Comment by scherztc** [comment]
<img width="1174" alt="screen shot 2018-03-14 at 2 28 40 pm" src="https://user-images.githubusercontent.com/5084562/37423436-39907eda-2794-11e8-8be6-8c64967c9594.png">

Should this be accomplished from the dashboard using the current filter tools?

**Comment by jamesvanmil** [comment]
Questions about this one:

* Thomas's question above - should we be able to accomplish this by filtering by collection on the dashboard, and then selecting all works for batch edit?
  * Note that this filter doesn't seem to work, as-is (e.g., I have a collection in my local environment, but it's only showing "Default Admin Set")
* Should the batch edit support both works and sub-collections?
* Do we already have support for batch-editing different classes simultaneously?
