### ISSUE TITLE
Use Capistrano for deployment

### ISSUE THREAD

**Issue by hortongn** [uclibs/ucrate#761]
### Descriptive summary

We want to be able to deploy Scholar to scholar-dev.uc.edu, scholar-qa.uc.edu, and scholar.uc.edu without having to use Bamboo.  The best alternative is probably https://capistranorb.com

After we get it working, we can decide if we want to use Capistrano as a backup when Bamboo is down, or just replace Bamboo entirely.

1. Learn about Capistrano
1. Configure it to deploy Scholar to curly.libraries.uc.edu
1. Get it working with the rest of our server environments (do test deploys on scholar-dev and scholar-qa)
1. Create detailed documentation on the Scholar wiki
1. Train the rest of the team how to use it
1. Bonus: investigate the other ways Capistrano can be used for non-deploy tasks (e.g. restarting sidekiq, etc.)

Notes:
* Be careful not to commit any sensitive passwords, keys, etc.
* Ask Glen for access to existing Bamboo deploy scripts

**Comment by hortongn** [comment]
@bsp3ars Some examples of Samvera apps using Capistrano:
* https://github.com/ucsblibrary/alexandria
* https://github.com/curationexperts/nurax
* https://github.com/curationexperts/laevigata
* https://github.com/osulp/Scholars-Archive
* https://github.com/OregonDigital/oregondigital
* https://github.com/psu-libraries/cho
* https://github.com/pulibrary/pul_solr
* https://github.com/pulibrary/figgy

**Comment by bsp3ars** [comment]
Progress
- [x] Local
- [x] Curly
- [ ] Dev
- [ ] QA
- [ ] Production
