### ISSUE TITLE
Creating DOI on existing work doesn't auto-fill the Publisher field

### ISSUE THREAD

**Issue by hortongn** [uclibs/ucrate#764]
### Descriptive summary

When editing an existing work and choosing to mint a new DOI, the publisher field is not being automatically populated with "University of Cincinnati."  

(It does work properly when creating a new work and new DOI at the same time)

### Expected behavior

If the Publisher field is blank, it gets automatically populated with "University of Cincinnati" when the user chooses to create a DOI

### Actual behavior

The Publisher field remains blank

### Steps to reproduce the behavior

1. Create a work without a DOI and with a blank publisher
1. Save the work
1. Edit the work and choose to mint a new DOI
1. Save the work
1. You will be returned to the edit form complaining that the Publisher field cannot be blank.

**Comment by scherztc** [comment]
Here are some notes about Rails 5 and Turbolinks : https://stackoverflow.com/questions/36110789/rails-5-how-to-use-document-ready-with-turbo-links

**Comment by bsp3ars** [comment]
Closed via https://github.com/uclibs/ucrate/pull/766
