### ISSUE TITLE
Export metadata from a collection

### ISSUE THREAD

**Issue by hortongn** [uclibs/ucrate#78]
### Descriptive summary

A user should be able to select a collection and export the metadata for all works in that collection to a CSV file that can be downloaded to their local machine.

Trello: https://trello.com/c/WwAQ7DJK/66-export-metadata

Depends on #108

**Comment by jamesvanmil** [comment]
Done looks like:

1. A button on the dashboard collection show page (e.g. `/dashboard/collections/PID`) labeled `Export metadata`
1. When the user clicks the button, they go to an index page of their metadata exports where the CSV file will appear for download when the file has been created.

* We'll set up MVC for this feature, and the button will post to a `MetadataExportController`
* Files for the export will be stored in the local database, along with basic administrative data about the request for metadata (e.g., collection pid/name, number of files, timestamp)

Issues for future enhancements should include:

* Notification of the user when the file is ready
* Processing of the metadata export by a background job

**Comment by hortongn** [comment]
@jamesvanmil That all looks good.  I suggest you make sure that the export button only shows for the user who owns the collection and for admins.  That is, the user should only see an export button if they can also see an `edit` button on that collection.

**Comment by newmanld** [comment]
I wonder if this is a question to confirm with P.O.s (if not done already) – whether metadata export should be available for those with view but not edit rights to a collection.

On an individual work, if Hyrax citation export features are incorporated (EndNote, Zotero, Mendeley) we do offer public export of metadata.

**Comment by jamesvanmil** [comment]
Blocked pending review of #109
