### ISSUE TITLE
Create procedure for ingesting large files

### ISSUE THREAD

**Issue by hortongn** [uclibs/ucrate#781]
### Descriptive summary

After the API issue (#750) is merged, try ingesting very large files to see if the API can reliably serve as our method for ingesting large (possibly > 100GB) files into Scholar.

We can test this with some of the large Woodman videos we have sitting on Isilon.

If the API has problems with large files, we need to either 1) change the API to work or 2) come up with another method for ingesting very large files.

Once we have a working solution, we can move on to #686

**Comment by bsp3ars** [comment]
We used the API to upload a 10GB file to http://curly.libraries.uc.edu:3002/concern/generic_works/1c18df763. After checking the md5's of my original copy and the uploaded version, they are identical. The next step is to try this on a different system with files bigger than 10 GB.
