### ISSUE TITLE
Reduce the deprecation and warning messages when running tests

### ISSUE THREAD

**Issue by hortongn** [uclibs/ucrate#80]
### Descriptive summary

See if we can get rid of messages like the following when we run the test suite:

`DEPRECATION WARNING: As of version 2.0.0, Samvera::NestingIndexer::Documents::PreservationDocument will be removed from the public API (called from <top (required)> at /home/travis/build/uclibs/ucrate/vendor/bundle/ruby/2.5.0/bundler/gems/hyrax-51b45cc2dc35/lib/hyrax/configuration.rb:3)`

DEPRECATION WARNING: ActiveSupport.halt_callback_chains_on_return_false= is deprecated and will be removed in Rails 5.2. (called from <top (required)> at /Users/Olivia/coop-spring/ucrate/config/initializers/new_framework_defaults.rb:23)

DEPRECATION WARNING: `#ignore` is deprecated and will be removed in 5.0. Please use `#transient` instead. (called from block (2 levels) in <top (required)> at /Users/Olivia/coop-spring/ucrate/spec/factories/users.rb:51)

`Passing 'script' command to redis as is; administrative commands cannot be effectively namespaced and should be called on the redis connection directly; passthrough has been deprecated and will be removed in redis-namespace 2.0 (at /home/travis/build/uclibs/ucrate/vendor/bundle/ruby/2.5.0/gems/redlock-0.2.2/lib/redlock/client.rb:129:in `load_scripts')`

`DEPRECATED: The :only_path option is deprecated in favor of the :ignore_query option`

**Comment by changy66** [comment]
Passing 'script' command to redis as is; administrative commands cannot be effectively namespaced and should be called on the redis connection directly; passthrough has been deprecated and will be removed in redis-namespace 2.0 (at /home/travis/build/uclibs/ucrate/vendor/bundle/ruby/2.5.0/gems/redlock-0.2.2/lib/redlock/client.rb:129:inload_scripts')` 

the file is 'spec/features/create_work_spec.rb '

**Comment by changy66** [comment]
DEPRECATED: The :only_path option is deprecated in favor of the :ignore_query option

The file is 'spec/features/delete_work_spec.rb '

**Comment by hortongn** [comment]
@changy66 Make sure any lines using the `have_link` matcher also use `href:`

Example:

change
`page.should have_link('Sign up', new_user_registration_path)`
to
`page.should have_link('Sign up', href: new_user_registration_path)`
