### ISSUE TITLE
Try the Hyrax batch ingest gem

### ISSUE THREAD

**Issue by hortongn** [uclibs/ucrate#811]
### Descriptive summary

There's a hyrax batch ingest gem that may be a good community-supported alternative to our current CSV upload implementation.

Let's see if it can be easily integrated into Scholar so we can test out it's features.  We will then want to demo it for Content Services to see if we all agree that it's a worthy addition.

The gem is located https://github.com/samvera-labs/hyrax-batch_ingest

There are also slides and an audio recording from a Samvera Virtual Connect 2019 session where this was demonstrated.  Probably a good idea to review that for details that may be missing on the README.

**Comment by scherztc** [comment]
hyrax-batch-ingest :  Developed by WGBH.  Integrates into the dashboard, but requires some inject type configuration with yml.  https://github.com/WGBH-MLA/ams/blob/develop/config/batch_ingest.yml.  Here is the Virtual Connect Presentation : https://wiki.lyrasis.org/display/samvera/Samvera+Virtual+Connect+2019+Program?preview=/108759543/112529229/Samvera_VirtualConnect_2019_batchingest.pdf.

**Comment by scherztc** [comment]
AMS (https://github.com/WGBH-MLA/ams).

DCE called Darlingtonia

Notch 8  https://github.com/notch8/BulkOps.

Bulkrax





4:44
I'd be more than happy to walk you through our implementation of hyrax-batch_ingest though. With the schools and daycares closed though, I"m down to 1/2 to 3/4 time. I mostly work afternoons and evenings.

Andrew Myers  5:12 PM
But, if you haven't looked at what Notch8 and DCE have re: batch ingest, I'd take a gander. I got the impression from Connect that they were both further along in the direction I was hoping to have gone with the hyrax-batch_ingest gem.

**Comment by scherztc** [comment]
Bulkrax: https://github.com/samvera-labs/bulkrax

LibXML Dependency SOLUTION : gem install libxml-ruby -v '3.0.0' -- --with-xml2-config=/usr/local/Cellar/libxml2/2.9.7/bin/xml2-config --with-xml2-dir=/usr/local/Cellar/libxml2/2.9.7/ --with-xml2-lib=/usr/local/Cellar/libxml2/2.9.7/lib/ --with-xml2-include=/usr/local/Cellar/libxml2/2.9.7/include/

**Comment by scherztc** [comment]
We have a branch of Scholar w/ Bulkrax installed on curly.libraries.uc.edu:3002. Same admin username and password. I would like to test this one with some test content. Check out the Dashboard. There are all kinds of importer/exporters/submission review/ manage exports. There still might be some configuration for our metadata and our test content. I can make the changes to the bulkrax.yml when needed. Here is the Bulkrax documentation : https://github.com/samvera-labs/bulkrax

**Comment by scherztc** [comment]
BulkRAX is the community supported solution from Notch8 that is full featured and fully integrated into the Dashboard.  We have decided to go with BulkRAX as our ingest/export gem for Scholar.

**Comment by scherztc** [comment]
DCE : https://github.com/curationexperts/zizia
