### ISSUE TITLE
New Classify Concern Page needs Spanish translations for Description

### ISSUE THREAD

**Issue by scherztc** [uclibs/ucrate#812]
### Descriptive summary

The Create Work Classify Concern Page needs the work type descriptions to translate into Spanish.  

### Expected behavior
That there be something Spanish in the work type descriptions.
### Actual behavior

<img width="1291" alt="Screen Shot 2019-09-19 at 10 46 16 AM" src="https://user-images.githubusercontent.com/5084562/65255261-92f11480-dacb-11e9-9637-4e646b20b597.png">

### Steps to reproduce the behavior

app/views/classify_concerns/new.html.erb

### Related work

Link to related issues or prior related work here.

**Comment by hortongn** [comment]
This is covered by issue #602
