### ISSUE TITLE
New Classify Concern Page needs Chinese translations for Description

### ISSUE THREAD

**Issue by scherztc** [uclibs/ucrate#813]
### Descriptive summary

The Create Work Classify Concern Page needs the work type descriptions to translate into Chinese.  

### Expected behavior
That there be something Chinese in the work type descriptions.

### Actual behavior
<img width="1202" alt="Screen Shot 2019-09-19 at 10 46 33 AM" src="https://user-images.githubusercontent.com/5084562/65255403-cf247500-dacb-11e9-8e65-fcd44ba65c57.png">

### Steps to reproduce the behavior

app/views/classify_concerns/new.html.erb

### Related work

Link to related issues or prior related work here.

**Comment by hortongn** [comment]
This is covered by issue #602
