### ISSUE TITLE
Enable uploads from cloud providers

### ISSUE THREAD

**Issue by hortongn** [uclibs/ucrate#86]
### Descriptive summary

Add the needed code and configuration to enable uploads from cloud providers using browse_everything.

Trello: https://trello.com/c/KUI7NlMT/100-enable-uploads-from-cloud-providers

**Comment by jamesvanmil** [comment]
Kaltura isn't working out of the box - might resize this issue.

**Comment by jamesvanmil** [comment]
For Box.com, getting a `redirect_uri_mismatch` error. Might need new credentials.
