### ISSUE TITLE
Unable to add child works from the relationship tab on the edit page.

### ISSUE THREAD

**Issue by scherztc** [uclibs/ucrate#862]
Unable to add child works to a parent work from the relationship tab on the edit page - the look-up is returning 0 results

**Comment by crowesn** [comment]
@scherztc 

I'm not able to replicate this but on local or production working with the develop branch.
I *am* able to add a child work when editing an existing work. I noticed however that the add child work dialog is not present on the relationships table when **creating a new work** is this expected functionality?

## Steps to reproduce
1. Create new work
2. Click Edit button 
3. Click Relationships tab
4. under *Other Works in this Work* add search string to *Find child work* field
5. Select child work from dropdown and click *add*
6. Save changes

**Comment by scherztc** [comment]
@crowesn :  I agree.  I tested with your ruby 2.7.1 and I didn't see a problem attaching children works.  I am going to ahead and close.
