### ISSUE TITLE
Update to ruby 2.6.x or 2.7.x, Hyrax to 2.9.x

### ISSUE THREAD

**Issue by hortongn** [uclibs/ucrate#883]
### Descriptive summary

ruby 2.5 has an EOL of March 31, 2021.  Before the end of 2020 we should update Scholar to work with ruby 2.6 or 2.7.

Using ruby 2.7 would require us to upgrade to at least Hyrax 2.8.0.  Earlier versions of Hyrax do not support ruby 2.7.

**Comment by crowesn** [comment]
- [ ]  app/assets/javascripts/hyrax/proxy_rights.js
- [ ]  app/assets/stylesheets/hyrax/dashboard.scss
- [ ]  app/controllers/concerns/hyrax/works_controller_behavior.rb
- [ ]  app/controllers/hyrax/batch_uploads_controller.rb
- [ ]  app/controllers/hyrax/collections_controller.rb
- [ ]  app/controllers/hyrax/contact_form_controller.rb
- [ ]  app/controllers/hyrax/dashboard/collections_controller.rb
- [ ]  app/controllers/hyrax/dashboard/profiles_controller.rb
- [ ]  app/controllers/hyrax/depositors_controller.rb
- [ ]  app/controllers/hyrax/file_sets_controller.rb
- [ ]  app/controllers/hyrax/uploads_controller.rb
- [ ]  app/controllers/hyrax/users_controller.rb
- [ ]  app/forms/hyrax/forms/batch_edit_form.rb
- [ ]  app/forms/hyrax/forms/batch_upload_form.rb
- [ ]  app/forms/hyrax/forms/collection_form.rb
- [ ]  app/indexers/hyrax/work_indexer.rb
- [ ]  app/jobs/attach_files_to_work_job.rb
- [ ]  app/jobs/batch_create_job.rb
- [ ]  app/jobs/fixity_check_job.rb
- [ ]  app/jobs/user_edit_profile_event_job.rb
- [ ]  app/models/batch_upload_item.rb
- [ ]  app/models/concerns/hyrax/basic_metadata.rb
- [ ]  app/models/hyrax/contact_form.rb
- [ ]  app/models/hyrax/statistic.rb
- [ ]  app/models/hyrax/uploaded_file.rb
- [ ]  app/presenters/hyrax/collection_presenter.rb
- [ ]  app/presenters/hyrax/presents_attributes.rb
- [ ]  app/renderers/hyrax/renderers/attribute_renderer.rb
- [ ]  app/services/hyrax/default_middleware_stack.rb
- [ ]  app/views/_controls.html.erb
- [ ]  app/views/_logo.html.erb
- [ ]  app/views/_masthead.html.erb
- [ ]  app/views/_user_util_links.html.erb
- [ ]  app/views/catalog/_index_header_list_collection.html.erb
- [ ]  app/views/catalog/_index_header_list_default.html.erb
- [ ]  app/views/catalog/_index_list_default.html.erb
- [ ]  app/views/catalog/_search_form.html.erb
- [ ]  app/views/hyrax/base/_attribute_rows.html.erb
- [ ]  app/views/hyrax/base/_citations.html.erb
- [ ]  app/views/hyrax/base/_form_files.html.erb
- [ ]  app/views/hyrax/base/_form_metadata.html.erb
- [ ]  app/views/hyrax/base/_form_permission.html.erb
- [ ]  app/views/hyrax/base/_form_progress.html.erb
- [ ]  app/views/hyrax/base/_form_relationships.html.erb
- [ ]  app/views/hyrax/base/_form_share.html.erb
- [ ]  app/views/hyrax/base/_form_visibility_component.html.erb
- [ ]  app/views/hyrax/base/_guts4form.html.erb
- [ ]  app/views/hyrax/base/_member.html.erb
- [ ]  app/views/hyrax/base/_metadata.html.erb
- [ ]  app/views/hyrax/base/_relationships.html.erb
- [ ]  app/views/hyrax/base/_relationships_parent_rows.html.erb
- [ ]  app/views/hyrax/base/_representative_media.html.erb
- [ ]  app/views/hyrax/base/_social_media.html.erb
- [ ]  app/views/hyrax/base/_work_description.erb
- [ ]  app/views/hyrax/base/show.html.erb
- [ ]  app/views/hyrax/batch_uploads/_form.html.erb
- [ ]  app/views/hyrax/collections/_show_descriptions.html.erb
- [ ]  app/views/hyrax/collections/_sort_and_per_page.html.erb
- [ ]  app/views/hyrax/collections/show.html.erb
- [ ]  app/views/hyrax/contact_form/_directions.html.erb
- [ ]  app/views/hyrax/contact_form/new.html.erb
- [ ]  app/views/hyrax/content_blocks/_form.html.erb
- [ ]  app/views/hyrax/dashboard/_index_partials/_proxy_rights.html.erb
- [ ]  app/views/hyrax/dashboard/_sidebar.html.erb
- [ ]  app/views/hyrax/dashboard/collections/_show_actions.html.erb
- [ ]  app/views/hyrax/dashboard/collections/_show_descriptions.html.erb
- [ ]  app/views/hyrax/dashboard/collections/edit.html.erb
- [ ]  app/views/hyrax/dashboard/collections/new.html.erb
- [ ]  app/views/hyrax/dashboard/collections/show.html.erb
- [ ]  app/views/hyrax/dashboard/profiles/_edit_primary.html.erb
- [ ]  app/views/hyrax/dashboard/profiles/show.html.erb
- [ ]  app/views/hyrax/dashboard/sidebar/_repository_content.html.erb
- [ ]  app/views/hyrax/dashboard/sidebar/_tasks.html.erb
- [ ]  app/views/hyrax/dashboard/works/_default_group.html.erb
- [ ]  app/views/hyrax/file_sets/media_display/_video.html.erb
- [ ]  app/views/hyrax/file_sets/show.html.erb
- [ ]  app/views/hyrax/homepage/_featured.html.erb
- [ ]  app/views/hyrax/homepage/_featured_researcher.html.erb
- [ ]  app/views/hyrax/homepage/_featured_works.html.erb
- [ ]  app/views/hyrax/homepage/_home_content.html.erb
- [ ]  app/views/hyrax/homepage/index.html.erb
- [ ]  app/views/hyrax/my/_collection_action_menu.html.erb
- [ ]  app/views/hyrax/my/_search_form.html.erb
- [ ]  app/views/hyrax/my/collections/_modal_delete_collections_deny.html.erb
- [ ]  app/views/hyrax/my/collections/_modal_delete_deny.html.erb
- [ ]  app/views/hyrax/my/works/index.html.erb
- [ ]  app/views/hyrax/notifications/_notifications.html.erb
- [ ]  app/views/hyrax/uploads/_js_templates.html.erb
- [ ]  app/views/hyrax/users/_search_form.html.erb
- [ ]  app/views/hyrax/users/_user_info.html.erb
- [ ]  app/views/hyrax/users/_user_row.html.erb
- [ ]  app/views/hyrax/users/_vitals.html.erb
- [ ]  app/views/hyrax/users/index.html.erb
- [ ]  app/views/layouts/_head_tag_content.html.erb
- [ ]  app/views/layouts/homepage.html.erb
- [ ]  app/views/layouts/hyrax.html.erb
- [ ]  app/views/records/edit_fields/_language.html.erb
- [ ]  app/views/records/edit_fields/_license.html.erb
- [ ]  app/views/records/edit_fields/_subject.html.erb
- [ ]  app/views/shared/_citations.html.erb
- [ ]  app/views/shared/_footer.html.erb

**Comment by crowesn** [comment]
## Review overrides

- [ ]  app/assets/javascripts/hyrax/proxy_rights.js
- [ ]  app/assets/stylesheets/hyrax/dashboard.scss
- [ ]  app/controllers/concerns/hyrax/works_controller_behavior.rb
- [ ]  app/controllers/hyrax/batch_uploads_controller.rb
- [ ]  app/controllers/hyrax/collections_controller.rb
- [ ]  app/controllers/hyrax/contact_form_controller.rb
- [ ]  app/controllers/hyrax/dashboard/collections_controller.rb
- [ ]  app/controllers/hyrax/dashboard/profiles_controller.rb
- [ ]  app/controllers/hyrax/depositors_controller.rb
- [ ]  app/controllers/hyrax/file_sets_controller.rb
- [ ]  app/controllers/hyrax/uploads_controller.rb
- [ ]  app/controllers/hyrax/users_controller.rb
- [ ]  app/forms/hyrax/forms/batch_edit_form.rb
- [ ]  app/forms/hyrax/forms/batch_upload_form.rb
- [ ]  app/forms/hyrax/forms/collection_form.rb
- [ ]  app/indexers/hyrax/collection_indexer.rb
- [ ]  app/indexers/hyrax/work_indexer.rb
- [ ]  app/jobs/attach_files_to_work_job.rb
- [ ]  app/jobs/batch_create_job.rb
- [ ]  app/jobs/fixity_check_job.rb
- [ ]  app/jobs/user_edit_profile_event_job.rb
- [ ]  app/models/batch_upload_item.rb
- [ ]  app/models/concerns/hyrax/basic_metadata.rb
- [ ]  app/models/hyrax/contact_form.rb
- [ ]  app/models/hyrax/statistic.rb
- [ ]  app/models/hyrax/uploaded_file.rb
- [ ]  app/presenters/hyrax/collection_presenter.rb
- [ ]  app/presenters/hyrax/presents_attributes.rb
- [ ]  app/renderers/hyrax/renderers/attribute_renderer.rb
- [ ]  app/services/hyrax/analytics.rb
- [ ]  app/services/hyrax/change_content_depositor_service.rb
- [ ]  app/services/hyrax/default_middleware_stack.rb
- [ ]  app/services/hyrax/fixity_check_failure_service.rb
- [ ]  app/views/_controls.html.erb
- [ ]  app/views/_logo.html.erb
- [ ]  app/views/_masthead.html.erb
- [ ]  app/views/_user_util_links.html.erb
- [ ]  app/views/catalog/_index_header_list_collection.html.erb
- [ ]  app/views/catalog/_index_header_list_default.html.erb
- [ ]  app/views/catalog/_index_list_default.html.erb
- [ ]  app/views/catalog/_search_form.html.erb
- [ ]  app/views/hyrax/base/_attribute_rows.html.erb
- [ ]  app/views/hyrax/base/_citations.html.erb
- [ ]  app/views/hyrax/base/_form_files.html.erb
- [ ]  app/views/hyrax/base/_form_metadata.html.erb
- [ ]  app/views/hyrax/base/_form_permission.html.erb
- [ ]  app/views/hyrax/base/_form_progress.html.erb
- [ ]  app/views/hyrax/base/_form_relationships.html.erb
- [ ]  app/views/hyrax/base/_form_share.html.erb
- [ ]  app/views/hyrax/base/_form_visibility_component.html.erb
- [ ]  app/views/hyrax/base/_guts4form.html.erb
- [ ]  app/views/hyrax/base/_member.html.erb
- [ ]  app/views/hyrax/base/_metadata.html.erb
- [ ]  app/views/hyrax/base/_relationships.html.erb
- [ ]  app/views/hyrax/base/_relationships_parent_rows.html.erb
- [ ]  app/views/hyrax/base/_representative_media.html.erb
- [ ]  app/views/hyrax/base/_social_media.html.erb
- [ ]  app/views/hyrax/base/_work_description.erb
- [ ]  app/views/hyrax/base/show.html.erb
- [ ]  app/views/hyrax/batch_uploads/_form.html.erb
- [ ]  app/views/hyrax/collections/_show_descriptions.html.erb
- [ ]  app/views/hyrax/collections/_sort_and_per_page.html.erb
- [ ]  app/views/hyrax/collections/show.html.erb
- [ ]  app/views/hyrax/contact_form/_directions.html.erb
- [ ]  app/views/hyrax/contact_form/new.html.erb
- [ ]  app/views/hyrax/content_blocks/_form.html.erb
- [ ]  app/views/hyrax/dashboard/_index_partials/_proxy_rights.html.erb
- [ ]  app/views/hyrax/dashboard/_sidebar.html.erb
- [ ]  app/views/hyrax/dashboard/collections/_show_actions.html.erb
- [ ]  app/views/hyrax/dashboard/collections/_show_descriptions.html.erb
- [ ]  app/views/hyrax/dashboard/collections/edit.html.erb
- [ ]  app/views/hyrax/dashboard/collections/new.html.erb
- [ ]  app/views/hyrax/dashboard/collections/show.html.erb
- [ ]  app/views/hyrax/dashboard/profiles/_edit_primary.html.erb
- [ ]  app/views/hyrax/dashboard/profiles/show.html.erb
- [ ]  app/views/hyrax/dashboard/sidebar/_repository_content.html.erb
- [ ]  app/views/hyrax/dashboard/sidebar/_tasks.html.erb
- [ ]  app/views/hyrax/dashboard/works/_default_group.html.erb
- [ ]  app/views/hyrax/file_sets/media_display/_video.html.erb
- [ ]  app/views/hyrax/file_sets/show.html.erb
- [ ]  app/views/hyrax/homepage/_featured.html.erb
- [ ]  app/views/hyrax/homepage/_featured_researcher.html.erb
- [ ]  app/views/hyrax/homepage/_featured_works.html.erb
- [ ]  app/views/hyrax/homepage/_home_content.html.erb
- [ ]  app/views/hyrax/homepage/index.html.erb
- [ ]  app/views/hyrax/my/_collection_action_menu.html.erb
- [ ]  app/views/hyrax/my/_search_form.html.erb
- [ ]  app/views/hyrax/my/collections/_modal_delete_collections_deny.html.erb
- [ ]  app/views/hyrax/my/collections/_modal_delete_deny.html.erb
- [ ]  app/views/hyrax/my/works/index.html.erb
- [ ]  app/views/hyrax/notifications/_notifications.html.erb
- [ ]  app/views/hyrax/uploads/_js_templates.html.erb
- [ ]  app/views/hyrax/users/_search_form.html.erb
- [ ]  app/views/hyrax/users/_user_info.html.erb
- [ ]  app/views/hyrax/users/_user_row.html.erb
- [ ]  app/views/hyrax/users/_vitals.html.erb
- [ ]  app/views/hyrax/users/index.html.erb
- [ ]  app/views/layouts/_head_tag_content.html.erb
- [ ]  app/views/layouts/homepage.html.erb
- [ ]  app/views/layouts/hyrax.html.erb
- [ ]  app/views/records/edit_fields/_language.html.erb
- [ ]  app/views/records/edit_fields/_license.html.erb
- [ ]  app/views/records/edit_fields/_subject.html.erb
- [ ]  app/views/shared/_citations.html.erb
- [ ]  app/views/shared/_footer.html.erb

**Comment by crowesn** [comment]
https://github.com/samvera/hyrax/blob/v2.9.3/app/controllers/hyrax/batch_uploads_controller.rb#L77

This line is excluded in our local override , I'm assuming because we don't use the field?

**Comment by crowesn** [comment]
- [ ]  app/assets/javascripts/hyrax/proxy_rights.js
- [ ]  app/assets/stylesheets/hyrax/dashboard.scss
- [ ]  app/controllers/concerns/hyrax/works_controller_behavior.rb
- [ ]  app/controllers/hyrax/batch_uploads_controller.rb
- [ ]  app/controllers/hyrax/collections_controller.rb
- [ ]  app/controllers/hyrax/contact_form_controller.rb
- [ ]  app/controllers/hyrax/dashboard/collections_controller.rb
- [ ]  app/controllers/hyrax/dashboard/profiles_controller.rb
- [ ]  app/controllers/hyrax/depositors_controller.rb
- [ ]  app/controllers/hyrax/file_sets_controller.rb
- [ ]  app/controllers/hyrax/uploads_controller.rb
- [ ]  app/controllers/hyrax/users_controller.rb
- [ ]  app/forms/hyrax/forms/batch_edit_form.rb
- [ ]  app/forms/hyrax/forms/batch_upload_form.rb
- [ ]  app/forms/hyrax/forms/collection_form.rb
- [ ]  app/indexers/hyrax/collection_indexer.rb
- [ ]  app/indexers/hyrax/work_indexer.rb
- [ ]  app/jobs/attach_files_to_work_job.rb
- [ ]  app/jobs/batch_create_job.rb
- [ ]  app/jobs/fixity_check_job.rb
- [ ]  app/jobs/user_edit_profile_event_job.rb
- [ ]  app/models/batch_upload_item.rb
- [ ]  app/models/concerns/hyrax/basic_metadata.rb
- [ ]  app/models/hyrax/contact_form.rb
- [ ]  app/models/hyrax/statistic.rb
- [ ]  app/models/hyrax/uploaded_file.rb
- [ ]  app/presenters/hyrax/collection_presenter.rb
- [ ]  app/presenters/hyrax/presents_attributes.rb
- [ ]  app/renderers/hyrax/renderers/attribute_renderer.rb
- [ ]  app/services/hyrax/analytics.rb
- [ ]  app/services/hyrax/change_content_depositor_service.rb
- [ ]  app/services/hyrax/default_middleware_stack.rb
- [ ]  app/services/hyrax/fixity_check_failure_service.rb
- [ ]  app/views/_controls.html.erb
- [ ]  app/views/_logo.html.erb
- [ ]  app/views/_masthead.html.erb
- [ ]  app/views/_user_util_links.html.erb
- [ ]  app/views/catalog/_index_header_list_collection.html.erb
- [ ]  app/views/catalog/_index_header_list_default.html.erb
- [ ]  app/views/catalog/_index_list_default.html.erb
- [ ]  app/views/catalog/_search_form.html.erb
- [ ]  app/views/hyrax/base/_attribute_rows.html.erb
- [ ]  app/views/hyrax/base/_citations.html.erb
- [ ]  app/views/hyrax/base/_form_files.html.erb
- [ ]  app/views/hyrax/base/_form_metadata.html.erb
- [ ]  app/views/hyrax/base/_form_permission.html.erb
- [ ]  app/views/hyrax/base/_form_progress.html.erb
- [ ]  app/views/hyrax/base/_form_relationships.html.erb
- [ ]  app/views/hyrax/base/_form_share.html.erb
- [ ]  app/views/hyrax/base/_form_visibility_component.html.erb
- [ ]  app/views/hyrax/base/_guts4form.html.erb
- [ ]  app/views/hyrax/base/_member.html.erb
- [ ]  app/views/hyrax/base/_metadata.html.erb
- [ ]  app/views/hyrax/base/_relationships.html.erb
- [ ]  app/views/hyrax/base/_relationships_parent_rows.html.erb
- [ ]  app/views/hyrax/base/_representative_media.html.erb
- [ ]  app/views/hyrax/base/_social_media.html.erb
- [ ]  app/views/hyrax/base/_work_description.erb
- [ ]  app/views/hyrax/base/show.html.erb
- [ ]  app/views/hyrax/batch_uploads/_form.html.erb
- [ ]  app/views/hyrax/collections/_show_descriptions.html.erb
- [ ]  app/views/hyrax/collections/_sort_and_per_page.html.erb
- [ ]  app/views/hyrax/collections/show.html.erb
- [ ]  app/views/hyrax/contact_form/_directions.html.erb
- [ ]  app/views/hyrax/contact_form/new.html.erb
- [ ]  app/views/hyrax/content_blocks/_form.html.erb
- [ ]  app/views/hyrax/dashboard/_index_partials/_proxy_rights.html.erb
- [ ]  app/views/hyrax/dashboard/_sidebar.html.erb
- [ ]  app/views/hyrax/dashboard/collections/_show_actions.html.erb
- [ ]  app/views/hyrax/dashboard/collections/_show_descriptions.html.erb
- [ ]  app/views/hyrax/dashboard/collections/edit.html.erb
- [ ]  app/views/hyrax/dashboard/collections/new.html.erb
- [ ]  app/views/hyrax/dashboard/collections/show.html.erb
- [ ]  app/views/hyrax/dashboard/profiles/_edit_primary.html.erb
- [ ]  app/views/hyrax/dashboard/profiles/show.html.erb
- [ ]  app/views/hyrax/dashboard/sidebar/_repository_content.html.erb
- [ ]  app/views/hyrax/dashboard/sidebar/_tasks.html.erb
- [ ]  app/views/hyrax/dashboard/works/_default_group.html.erb
- [ ]  app/views/hyrax/file_sets/media_display/_video.html.erb
- [ ]  app/views/hyrax/file_sets/show.html.erb
- [ ]  app/views/hyrax/homepage/_featured.html.erb
- [ ]  app/views/hyrax/homepage/_featured_researcher.html.erb
- [ ]  app/views/hyrax/homepage/_featured_works.html.erb
- [ ]  app/views/hyrax/homepage/_home_content.html.erb
- [ ]  app/views/hyrax/homepage/index.html.erb
- [ ]  app/views/hyrax/my/_collection_action_menu.html.erb
- [ ]  app/views/hyrax/my/_search_form.html.erb
- [ ]  app/views/hyrax/my/collections/_modal_delete_collections_deny.html.erb
- [ ]  app/views/hyrax/my/collections/_modal_delete_deny.html.erb
- [ ]  app/views/hyrax/my/works/index.html.erb
- [ ]  app/views/hyrax/notifications/_notifications.html.erb
- [ ]  app/views/hyrax/uploads/_js_templates.html.erb
- [ ]  app/views/hyrax/users/_search_form.html.erb
- [ ]  app/views/hyrax/users/_user_info.html.erb
- [ ]  app/views/hyrax/users/_user_row.html.erb
- [ ]  app/views/hyrax/users/_vitals.html.erb
- [ ]  app/views/hyrax/users/index.html.erb
- [ ]  app/views/layouts/_head_tag_content.html.erb
- [ ]  app/views/layouts/homepage.html.erb
- [ ]  app/views/layouts/hyrax.html.erb
- [ ]  app/views/records/edit_fields/_language.html.erb
- [ ]  app/views/records/edit_fields/_license.html.erb
- [ ]  app/views/records/edit_fields/_subject.html.erb
- [ ]  app/views/shared/_citations.html.erb
- [ ]  app/views/shared/_footer.html.erb
