### ISSUE TITLE
Test deploys to scholar-dev and scholar-qa

### ISSUE THREAD

**Issue by hortongn** [uclibs/ucrate#907]
### Descriptive summary

Make sure that we can successfully deploy the current application to our dev and qa environments.  

Fix any blockers with the deploy.

**Comment by scherztc** [comment]
Deployed Successfully to DEV : Deployed on 02-18-2021 12:56:57 PM

**Comment by scherztc** [comment]
Deployed Successfully to QA (after solving uglifier problem) : Deployed on 02-18-2021 02:03:32 PM

**Comment by scherztc** [comment]
Deployment
Deploy using Capistrano
Scholar@UC App Workflow
Scholar@UC Deployment Procedure

**Comment by scherztc** [comment]
This PR fixes the Uglifier problem.  https://github.com/uclibs/ucrate/pull/909
