### ISSUE TITLE
Make x-ray configurable based on environmental variable

### ISSUE THREAD

**Issue by scherztc** [uclibs/ucrate#937]
### Descriptive summary

We need to be able to turn on x-ray in our test and local environments.

### Expected behavior

Expect the initializer to have condition similiar to 
https://github.com/uclibs/ucrate/blob/develop/config/initializers/clamav.rb

### Steps to reproduce the behavior

1. Do this
1. Then do this...

### Related work

Link to related issues or prior related work here.

**Comment by bsp3ars** [comment]
Found this on the official xray github https://github.com/aws/aws-xray-sdk-ruby/issues/52
