### ISSUE TITLE
Batch Upload Mass Assignment Vulnerability: Medium

### ISSUE THREAD

**Issue by bsp3ars** [uclibs/ucrate#941]
### Descriptive summary
Brakeman found a vulnerability with file: app/controllers/hyrax/batch_uploads_controller.rb on line 16

Brakeman Message:

Confidence: Medium
Category: Mass Assignment
Check: MassAssignment
Message: Specify exact keys allowed for mass assignment instead of using permit! which allows any keys
Code: params[:title].permit!
File: app/controllers/hyrax/batch_uploads_controller.rb
Line: 16

**Comment by crowesn** [comment]
This pattern is current upstream on hyrax/main https://github.com/samvera/hyrax/blob/main/app/controllers/hyrax/batch_uploads_controller.rb#L77
