### ISSUE TITLE
Upgrade Fedora to 4.7.5

### ISSUE THREAD

**Issue by hortongn** [uclibs/ucrate#949]
### Descriptive summary

Our server environments are using Fedora 4.7.3, but it has a vulnerability reported by Info Sec with Apache Struts.  Struts is embedded in the Fedora install, but has been removed from Fedora 4.7.5.  

This upgrade will not require content migration.  It's just a drop-in replacement for Fedora.

**Comment by scherztc** [comment]
We were able to update our fcrepo_wrapper to 4.7.5 in our local environments.
CircleCI was already set to 4.7.5.

The next step is to use the Puppet/Vagrant approach to manually upgrade the .war file in our development environment.

https://github.com/uclibs/scholar-puppet-vagrant/blob/scholar-3-update/modules/fcrepo/manifests/init.pp

**Comment by scherztc** [comment]
Fedora
- As the root user, stop fedora with /opt/tomcat/bin/shutdown.sh
- download fcrepo-webapp-4.7.5.war from https://github.com/fcrepo/fcrepo/releases/tag/fcrepo-4.7.5
- rename fcrepo-webapp-4.7.5.war to fedora.war and replace the file in /opt/tomcat/webapps/fedora.war
- As the root user, start fedora with runuser -l tomcat -c '/mnt/hydra/fcrepo/etc/fcrepo_start.sh'

**Comment by scherztc** [comment]
Successfully deployed fedora 4.7.5
