### ISSUE TITLE
Upgrade to Hyrax 2.9.6

### ISSUE THREAD

**Issue by scherztc** [uclibs/ucrate#953]
Review Change Log.

**Comment by crowesn** [comment]
https://github.com/samvera/hyrax/compare/v2.9.4...v2.9.6

**Comment by crowesn** [comment]
Overrides:
- [ ] app/controllers/concerns/hyrax/works_controller_behavior.rb
- [ ] app/views/catalog/_search_form.html.erb
- [ ] app/views/hyrax/batch_uploads/_form.html.erb
