### ISSUE TITLE
Deprecation Warning : DISTINCT

### ISSUE THREAD

**Issue by scherztc** [uclibs/ucrate#993]
DEPRECATION WARNING: Dangerous query method (method whose arguments are used as raw SQL) called with non-attribute argument(s): "DISTINCT agent_id". Non-attribute arguments will be disallowed in Rails 6.0. This method should not be called with user-provided values, such as request parameters or model attributes. Known-safe values can be passed by wrapping them in Arel.sql(). (called from create at /Users/scherztc/Workspaces/ucrate/app/controllers/hyrax/dashboard/collections_controller.rb:21)

How to recreate : bundle exec rake spec

Done looks like : No warning when running test.

**Comment by Janell-Huyck** [comment]
I tracked down the source of this deprecation warning.  It is inside Hyrax, in the file: /gems/hyrax-2.9.6/app/services/hyrax/collection_types/permissions_service.rb.  Inside it, we are calling two different queries that are potentially unsafe:
`groups = Hyrax::CollectionTypeParticipant.joins(:hyrax_collection_type).where(hyrax_collection_type_id: collection_type.id,
                                                                                      agent_type: Hyrax::CollectionTypeParticipant::GROUP_TYPE,
                                                                                      access: Hyrax::CollectionTypeParticipant::MANAGE_ACCESS).pluck('DISTINCT agent_id')
        `
        and
        `Hyrax::CollectionTypeParticipant.joins(:hyrax_collection_type).where(hyrax_collection_type_id: collection_type.id,
                                                                             agent_type: Hyrax::CollectionTypeParticipant::USER_TYPE,
                                                                             access: Hyrax::CollectionTypeParticipant::MANAGE_ACCESS).pluck('DISTINCT agent_id')
      `
In my local copy of Hyrax 5.0.0, these same vulnerabilities are present in the permissions_service file.

We could silence the warnings, attempt to overwrite the gem, or ignore this deprecation warning.

**Comment by scherztc** [comment]
https://github.com/samvera/hyrax/commit/9ab079cd892d7c1cbb88a54464558575481a5d46#diff-57f80ce44265ce0550248402943bec949a3d9bdbd37384b57fa80f7830bab4e7
